### ISSUE TITLE
All projects overview

### ISSUE THREAD

**Issue by frantisekrusnak** [m2ms/fragalysis-frontend#11]
As a user I want to see the list of my projects, so I can choose one to continue with.

-	Project are displayed in the table:
o	Name
o	Target
o	Tags
o	Author
o	Created At
o	Actions - Delete project

**Comment by veronikabelusikova** [comment]
- [ ] As a user I want to see the list of my projects, so I can choose one to continue with.

- [ ] The application shall not display projects of other users except participants added to the project by author
- [ ] Project are displayed in the table:
o Title
o Author
o Tags
- [ ] Details of the project are displayed on mouse hover

**Comment by tibor-postek-m2ms** [comment]
Bug - after creating new project from scratch is not automatically created snapshot
