### ISSUE TITLE
Blank screen after selecting vector

### ISSUE THREAD

**Issue by boriskovar-m2ms** [m2ms/fragalysis-frontend#117]
Select target EPB41L3A
Select Site 2
for fragment x0076_1 display vectors
select highlighted vector
![image](https://user-images.githubusercontent.com/16878338/75249221-1d097b80-57d6-11ea-867e-61b0a1f6ee37.png)
Blank screen is displayed

**Comment by tibor-postek-m2ms** [comment]
- [ ] Open snack bar with message Something went wrong
- [ ] fix blank screen

**Comment by tibor-postek-m2ms** [comment]
BE response 500, but now without blank page
![image](https://user-images.githubusercontent.com/57392303/75851526-3455f380-5dea-11ea-86c9-bcf7291c21a7.png)
