### ISSUE TITLE
Scribble on screenshot in 'submit idea' modal

### ISSUE THREAD

**Issue by reskyner** [m2ms/fragalysis-frontend#120]
Ability to annotate the captured screenshot when submitting an idea. The modal should also be bigger and expandable

**Comment by phraenquex** [comment]
Priority 1:  evaluate whether this is easy to do.  If it is, it should be priority.

**Comment by matej-vavrek** [comment]
This should not take more than a day top. There are already available libraries for drawing (react including) and it should not be so hard to do without a library too.

**Comment by matej-vavrek** [comment]
Scribble possibility was added. Modal dialog is currently set to fit at least 960 wide monitor. Modal is not resizable at the moment, but whole screenshot is scrollable.
