### ISSUE TITLE
When loading visual things, don't white everything out - merely inactivate all buttons, with a small "loading" modal

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#122]
- Version: 0.1.0
- Name: Frank von Delft
- Description: Currently, when I activate a ligand or something, the whole screen goes white - this is spectacularly annoying, because it distracts my eyes from what they were looking at.

Much better (probably): 
* just a progress bar (or similar) along the top (or bottom)
* turn the cursor into arrow with hourglass
* inactivate all the display toggles - e.g. so the mouse doesn't change to a hand when hovering over it.  That way, the user will know what's happening but not be frustrated. 
* (Maybe the progress bar can be displayed next to the mouse cursor?)

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/screenshot-1582640255456551001.png?raw=true)

**Comment by phraenquex** [comment]
This is surely a _very_ quick fix - please priorities.

**Comment by phraenquex** [comment]
What's really important is that anything visual does not disappear:  the user needs it to orient themselves by.  Simply inactivate.

**Comment by phraenquex** [comment]
Not necessary to be responsive in ANY way - just don't hide things.  That includes NGL view.

**Comment by matej-vavrek** [comment]
- added progress bar under header instead of the loading circle
- cursor changed into arrow with hourglass
- "anti-interaction" layer made transparent

**Comment by phraenquex** [comment]
Great!  Please _always_ post_ a snapshot before or after testing.  To give us single-click access to whatever it was you were looking at.

**Comment by phraenquex** [comment]
It's great!  Please merge and publish...
