### ISSUE TITLE
Invalid number of compounds for fragment

### ISSUE THREAD

**Issue by boriskovar-m2ms** [m2ms/fragalysis-frontend#125]
Number of compounds doesn't reflects real number of compounds is lower. Site 3, compound X0337_1. Displayed count is 176 and real count is 48.

Please investigate if we are calculating this number correctly. If it is correct calculation based on the data from backend (i.e. the data from backend are invalid), then remove the number of compounds from Hit navigator and from the header of compound navigator 

![image](https://user-images.githubusercontent.com/16878338/75352991-ecdfdc80-58aa-11ea-8b3c-dbda6bbc1f65.png)
![image](https://user-images.githubusercontent.com/16878338/75353028-fa956200-58aa-11ea-9341-aace014059a2.png)

**Comment by tibor-postek-m2ms** [comment]
- [ ] comment this feature
