### ISSUE TITLE
[Application] Changes in existing session are not saved

### ISSUE THREAD

**Issue by veronikabelusikova** [m2ms/fragalysis-frontend#126]
When I open existing session (saved session) and make some changes, then I click Save session as button - there are three possibilities (Copy link, open in new tab, close) - any of them does not work correctly, changes are not saved. Save session button does not work at all - no action is perfomed.

**Comment by zemiacsik** [comment]
Desired behaviour is:
- [ ] "Save session" just save the current session and continue with it
- [ ] "Save session as" create a new session and continue with the new one
- [ ] "Share snapshot" create a snapshot (session) and continue with the original session

**Comment by matej-vavrek** [comment]
Desired behaviour is:
- [ ] "Save session" just save the current session and continue with it
- [ ] "Save session as" create a new session and continue with the new one
- [ ] "Share snapshot" create a snapshot (session) and continue with the original session

**Comment by boriskovar-m2ms** [comment]
Does this issues still persist?
