### ISSUE TITLE
Sessions list loading indicator

### ISSUE THREAD

**Issue by boriskovar-m2ms** [m2ms/fragalysis-frontend#132]
On the home page the sessions are loading and before the sessions list is populated the wrong information about not having any sessions is displayed to the user.

![image](https://user-images.githubusercontent.com/16878338/75557993-5c87d000-5a41-11ea-980c-c150fd1914b5.png)

**Comment by tibor-postek-m2ms** [comment]
I've added loading indicators to target and project list

**Comment by tibor-postek-m2ms** [comment]
https://github.com/xchem/fragalysis-frontend/pull/173
