### ISSUE TITLE
Behaviour of the "All" display icon needs tweaking

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#148]
- Version: 0.1.0
- Name: Frank von Delft
- Description: Clicking on the [A] button for a compound is not intuitive:

* when everything or nothing is displayed - it works as expected

* when only soe things are displayed - it sometimes turns things off, sometimes on, but there's no way of knowing which it will be.

(Watch the movie of the last minute.)

I suggest:  if only some things are displayed, clicking it should always first turn everything off.  And make it "half-coloured", i.e. not completely blue, but not light-blue either, to make it more obvious what the click will do.

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/screenshot-1583173518848699806.png?raw=true)

**Comment by matej-vavrek** [comment]
We have changed the styling of selected buttons so you can see to which state are you going acter click + behaviour of "All" button to always deselect at first if some option is already selected and also it has new visual if some option is selected:
![image](https://user-images.githubusercontent.com/60509086/75982082-153c8c00-5ee6-11ea-9453-da0761967a80.png)
@phraenquex  Could you please [check this here](https://fragalysis-matej.apps.xchem.diamond.ac.uk/) if it is ok this way, please?

**Comment by phraenquex** [comment]
Perfect - please push to production.
Thank you!!

**Comment by phraenquex** [comment]
This is not yet in production - please issue pull request. Reopening.

**Comment by matej-vavrek** [comment]
It is in - https://github.com/xchem/fragalysis-frontend/pull/145, it just need to "bubble up".
