### ISSUE TITLE
Download fails on staging

### ISSUE THREAD

**Issue by mwinokan** [m2ms/fragalysis-frontend#1494]
I am unable to download structures from A71EV2A on staging

**Comment by mwinokan** [comment]
Duplicates #1491

**Comment by alanbchristie** [comment]
This seems to be a duplicate of #1491 where the b/e is creating a **SessionProject** object but the incoming object is missing some key properties, with the error: -

```
There is no Project at 'target__project_id' (session_project__target__project_id) - vars(base_start_obj)={'_state': <django.db.models.base.ModelState object at 0x7f4013da7e10>, 'id': 14, 'title': 'READ_ONLY', 'init_date': datetime.datetime(2024, 9, 3, 8, 11, 8, 737795, tzinfo=<UTC>), 'description': 'READ_ONLY', 'target_id': 5, 'project_id': 2, 'author_id': 7, 'tags': '[]'}
```

When creating **SessionProject** objects form the REST API everything is fine.
