### ISSUE TITLE
Snapshot didn't capture all the display modifications

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#152]
- Version: 0.1.0
- Name: Frank von Delft
- Description: After customising the display (using the Display Settings tool, and resulting in what's in the screenshot), I clicked on "Share snapshot".

When I loaded the URL in a new tab, the result didn't look like what I'd wanted to capture:  showed only ligand, and the hit navigator was funky (including no 2D structures displayed).

Here's the URL that was generated.
https://fragalysis.diamond.ac.uk/viewer/react/snapshot/16f82393-ee8b-4288-aaf9-34f159456a65

I'll capture the bad rendering in a new "Report issue" snapshot - giving it the same title.

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/screenshot-1583262748405335320.png?raw=true)

**Comment by phraenquex** [comment]
If this is easy to fix, can you treat it as critical?  (If not, we'll think of a work-around.)  Because I'm hoping to use this feature for broadcasting these particular structures to Coronavirus researchers.

**Comment by matej-vavrek** [comment]
On the first notice, there are some differencies between MPRO in snashot and available version of MPRO:
- Sites - snapshot has Site 1 and Site 2, available MPRO has only Site 1


I have tried to share snapshot of MPRO with some changes is display controls and it look same:

**Comment by matej-vavrek** [comment]
On the first notice, there are some differencies between MPRO in given snashot and current available version of MPRO:
- Sites - snapshot has Site 1 and Site 2, available MPRO has only Site 1
- requested data:
  - mol_groups ids are different - 223767 vs 224101
  - name of loaded files are different - Mpro-x0072_0_apo.pdb vs Mpro-x0072_0_apo_KUBsbNG.pdb (etc), snaphsot files return 404 as not found
  - ids of molecules are also different - 18466-18473 vs 18494-184950, snapshot images returns 404 as not found, but annotations looks fine

I have tried to share snapshot of MPRO with some changes in display controls and it look same:
https://fragalysis.diamond.ac.uk/viewer/react/snapshot/8464bd12-1268-49ea-9746-4322f1aa345e

So from my point of view it looks like the data on the backend for MPRO was changed and some are not available anymore. @phraenquex are we able to check this, please?

**Comment by phraenquex** [comment]
You can close the ticket - it was a non-issue, but I was unable to close or delete it.  Thanks for looking into it.
Frank

**Comment by phraenquex** [comment]
It seems to work now - thank you for looking and/or fixing so quickly!!

(Yes, the data did change, and I didn't know.  Rachael promises me she will not change data on the live system again...

**Comment by phraenquex** [comment]
Rachael just tells me I shouldn't close things - obviously (duh). 
Please push to production.

**Comment by zemiacsik** [comment]
I think there is nothinh to push to production in this case because this is (and was) current state of application or could you correct me, please? Is there still missing something in snapshots?

**Comment by matej-vavrek** [comment]
I think there is nothinh to push to production in this case because this is (and was) current state of application or could you correct me, please? Is there still missing something in snapshots?

**Comment by phraenquex** [comment]
It is definitely not the current state of the production application.  So something needs to be pushed.

On 05/03/2020 19:45, matej wrote:

I think there is nothinh to push to production in this case because this is (and was) current state of application or could you correct me, please? Is there still missing something in snapshots?

**Comment by matej-vavrek** [comment]
Ok, we will try to do a more investigation on this one.

**Comment by boriskovar-m2ms** [comment]
Actually we didn't fix a thing regarding this issue. We just investigated and found out that data changed between saving the snapshot and opening the snapshot. There is nothing to push regarding this issue.

**Comment by phraenquex** [comment]
Yes, sorry, I see I misunderstood your investigations and comments.  The production behaviour IS correct, and it does indeed require no change.  Now I will close this.
