### ISSUE TITLE
Snapshot didn't capture all the display modifications (II)

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#153]
- Version: 0.1.0
- Name: Frank von Delft
- Description: (See description in ticket submitted with same title.)

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/screenshot-1583262786677982463.png?raw=true)

**Comment by phraenquex** [comment]
It seems to work now - thank you for looking!
