### ISSUE TITLE
Displayed vectors look wrong (to a chemist) - a Fragment Network issue?

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#157]
- Version: 0.1.0
- Name: Anthony Aimon
- Description: This compound should have many green vectors, its a standard urea.
Any idea why all the vectors are red?
Thanks

Anthony

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/screenshot-1583330159857114754.png?raw=true)

**Comment by phraenquex** [comment]
Rachael, can you evaluate?  If it is a bug, then it's a priority issue.

**Comment by reskyner** [comment]
Yep, it's a bug. If you click on the vectors, there are some compounds.

**Comment by phraenquex** [comment]
Duplicate of #161 - close now.
