### ISSUE TITLE
Restore project from the snapshot

### ISSUE THREAD

**Issue by frantisekrusnak** [m2ms/fragalysis-frontend#16]
As a user I want to restore project from the snapshot displayed on the timeline.

-	Project will continue from the restored snapshot
-	The Application will keep snapshot after selected one until new snapshot is created
-	The Application shall ask before snapshot is open / actual work is saved and closed

**Comment by tibor-postek-m2ms** [comment]
- [ ] The Application shall ask before snapshot is open / actual work is saved and closed
