### ISSUE TITLE
[Application] "Clear selection" button in Hit cluster selector clears only selected parts in NGL viewer

### ISSUE THREAD

**Issue by veronikabelusikova** [m2ms/fragalysis-frontend#167]
Session where few sites and their parts are selected, displayed in NGL viewer. 

When I click "Clear selection", all parts except protein are cleared from NGL viewer, but selected sites in Hit cluster selector and parts of molecules in Hit navigator are still displayed. 
![clear selection](https://user-images.githubusercontent.com/60730965/76301506-a59c1780-62be-11ea-93a9-efe24721a270.PNG)

**Comment by veronikabelusikova** [comment]
Same behaviour when filter window is opened. 
Clear selction button does not close the window.

**Comment by veronikabelusikova** [comment]
When I select another part to NGL viewer, only "new" parts are displayed in NGL viewer, but in Hit navigator all parts (new and "cleared") are highlighted. 
In the picture - highlighted molecules are those, which should by cleared
![hit navigator](https://user-images.githubusercontent.com/60730965/76302828-f280ed80-62c0-11ea-9b57-20c236846d59.PNG)

**Comment by tibor-postek-m2ms** [comment]
please look at #250 .I think, that solution is there
