### ISSUE TITLE
[Application] Shift+click does not work

### ISSUE THREAD

**Issue by veronikabelusikova** [m2ms/fragalysis-frontend#168]
Fragalysis version 0.3.0

[Application] Shift+click does not work --> selected compound has light colourm but it is not displayed in NGL viewer.

**Comment by reskyner** [comment]
This is an annoying one. I believe the stack code needs updating to reflect the correct version of fragalysis (currently 0.0.1 by default, should be 2.x)

To manually fix, in open shift console:

`pip install --upgrade fragalysis
./launch_stack.sh`

You can email/slack informatics matters and ask them to fix this.

**Comment by reskyner** [comment]
I've just updated the requirements.txt file for the back-end. That should fix the issue. I will re-open if not.
