### ISSUE TITLE
Mpro-x010 fragment growing idea

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#169]
- Version: 0.2.2
- Name: Matthias Bauer
- Description: Hi, here is a quick idea for growing the fluoroindole fragment (x010) via merging with other fragments and aiming to harness a Met-chloro halogen bond. Best wishes, Matthias

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/screenshot-1583842137429427535.png?raw=true)

**Comment by MatthiasRB** [comment]
Can you please rename the title to "Mpro-x010 fragment growing idea". Many thanks!

**Comment by phraenquex** [comment]
Not something for github...  we'll transfer to elsewhere.

**Comment by toniyol** [comment]
Possible to get the email address of submitter -
for safekeeping, web submission is here: https://covid.postera.ai/covid/submissions/deadff56-4372-4cc7-a9f0-34fa9fdbb25d
