### ISSUE TITLE
[Application] Download CSV in Summary info does not work

### ISSUE THREAD

**Issue by veronikabelusikova** [m2ms/fragalysis-frontend#170]
[Application] Download CSV in Summary info does not work. When I click download CSV button, file is not downloaded. 
![picturemessage_ypm3l5b2 0nh](https://user-images.githubusercontent.com/60730965/76311234-c5d4d200-62d0-11ea-802f-249deeddbfa8.png)

**Comment by matej-vavrek** [comment]
There were some changes in colour system which caused error in getting attributes of colour. So maybe further discussion is advised.
It had this header: 'smiles', 'mol', 'vector', 'classNumber', 'class', 'classColors'
Current header: 'smiles', 'mol', 'vector', 'class', 'classColor'
'class ' is name of label (what you name had typed)
'classColor' is name of color
