### ISSUE TITLE
Fix in database:  update the json of a specific snapshot which is currently broken.

### ISSUE THREAD

**Issue by phraenquex** [m2ms/fragalysis-frontend#177]
This snapshot has gone out to the world, in various blogposts and twitter and stuff: 
   https://fragalysis.diamond.ac.uk/viewer/react/snapshot/4c6c8fb1-f072-4b17-b948-5b6eeec0ebf1

However, it does not now render correctly (no idea why;  ticket is #175).

Meanwhile, we urgently need that specific snapshot fixed.

So please replace the underlying json for that snapshot with the json in this snapshot:
    https://fragalysis.diamond.ac.uk/viewer/react/snapshot/4c6c8fb1-f072-4b17-b948-5b6eeec0ebf1

Please do it immediately - it's quite a Public Relations crisis.

**Comment by boriskovar-m2ms** [comment]
The link to second snapshot is the same as for the first snapshot

**Comment by phraenquex** [comment]
Sorry, this is the correct new snapshot:
https://fragalysis.diamond.ac.uk/viewer/react/snapshot/9b3da80c-5ea2-4f7f-b795-691d6d558bbf

Anna, you have access to the production DB, right?  Can you look at the tables and decide if you know how to do this?  As DB operation it's trivial, but of course only if you know what you're meant to change.

**Comment by tibor-postek-m2ms** [comment]
Snapshot is still incorrect. There are missing following objects: molecule groups (blue spheres in summary NGL view) and protein in Major NGL view

![obrázok](https://user-images.githubusercontent.com/57392303/76395001-b4460580-6376-11ea-8838-76813c90eaa8.png)

**Comment by tdudgeon** [comment]
I hope its done:

```
mysql> update scoring_viewscene set uuid = 'dummy_uuid_fix_issue_177________' where uuid='9b3da80c5ea24f7fb795691d6d558bbf';
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> update scoring_viewscene set uuid = '9b3da80c5ea24f7fb795691d6d558bbf' where uuid='4c6c8fb1f0724b17b9485b6eeec0ebf1';
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0
```

This changed the UUID of the first link to the UUID of the second.

@phraenquex Can you test this out?

**Comment by phraenquex** [comment]
No, that broke the scene entirely;  Tim, please restore to the original value.

Tibor:  I suspect the json in the "scence" field of that record makes reference to other records in the database (model, molecule);  do understand the json enough to be able to figure out what other things need to be copied across from the new scene?

**Comment by tdudgeon** [comment]
@phraenquex the original uuids have been reset

**Comment by phraenquex** [comment]
Thanks @tdudgeon Tim.
@tibor-postek-m2ms , @boriskovar-m2ms , please comment on my question a few minutes ago.

**Comment by boriskovar-m2ms** [comment]
@tibor-postek-m2ms this has the highest priority right now

**Comment by tibor-postek-m2ms** [comment]
When you load objects, you want to obtain pdb file from Back End 
<img width="822" alt="obrázok" src="https://user-images.githubusercontent.com/57392303/76411189-91751a80-6391-11ea-926d-35ccd971aa27.png">

and when you open Network tab in inspector, you will see, that these files are not founded
![obrázok](https://user-images.githubusercontent.com/57392303/76411279-c7b29a00-6391-11ea-82c4-63ed26f3ed1f.png)

**Comment by tibor-postek-m2ms** [comment]
When we parse newest restored data, there are only 3 objects to load 
![obrázok](https://user-images.githubusercontent.com/57392303/76413071-0ac23c80-6395-11ea-98fe-3791558293b9.png)
this snapshot https://fragalysis.diamond.ac.uk/viewer/react/snapshot/9b3da80c-5ea2-4f7f-b795-691d6d558bbf has  17 objects to load in NGL View
![obrázok](https://user-images.githubusercontent.com/57392303/76413141-2d545580-6395-11ea-98c0-246901fe586c.png)

The result is, that restored data are wrong !

**Comment by phraenquex** [comment]
@tibor-postek-m2ms - you can stop working on it:  Tim fixed it.

**Comment by phraenquex** [comment]
The previous thing he tried (switching UUIDs) failed;  what he had to do was copy the actual json text from the new to the old record.

**Comment by phraenquex** [comment]
Thank you very much for your work, all!  And apologies the last-minute flap - I promise to try and keep them to a minimum....
