### ISSUE TITLE
Allow additional sort fields: (a) site number and (b) molecule ID

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#183]
- Version: 0.2.2
- Name: Frank von Delft
- Description: The sites currently show up in the Hit navigator sorted site number and then hit/molecule ID.  
I want to be able to resort them by hit ID;  or make sorting by site a secondary sorting criterion.
So make those both sortable properties.

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/screenshot-1584042749033822371.png?raw=true)

**Comment by matej-vavrek** [comment]
Added sort options for site ID and hit ID:
https://fragalysis-matej.apps.xchem.diamond.ac.uk/viewer/react/landing

**Comment by veronikabelusikova** [comment]
tested on: 
https://fragalysis-matej.apps.xchem.diamond.ac.uk/viewer/react/snapshot/c1a777e2-ca87-480e-81fb-078899835876

**Comment by phraenquex** [comment]
Awesome! Moving to next swim-lane, please move to production.
