### ISSUE TITLE
Make it more obvious how to download list of SMILES or compound IDs

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#184]
- Version: 0.2.2
- Name: Patrick
- Description: Hi Rachael (I presume?), Nice work on Fragalysis! It's looking awesome. One thing that would be cool - if we could download the list of compound IDs/SMILES. All of them, or based on the filter, site selected. Keep it up!

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/screenshot-1584096605455775854.png?raw=true)

**Comment by phraenquex** [comment]
Rachael, is there a quick win here?
