### ISSUE TITLE
"Share snapshot" takes very very long when there are many objects

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#189]
- Version: 0.2.2
- Name: Frank von Delft
- Description: The snapshot below (URL) took >2 minutes to generate, the first time I clicked "share snapshot".  

Either the code needs optimising, or it needs a progress bar, or both.

https://fragalysis.diamond.ac.uk/viewer/react/snapshot/0a084a18-8329-4540-b2c3-667852e15518

However, note:  when I clicked the button again, straight afterwards, it took <20 seconds.  This could either be because it was the second time I clicked for the same scene (lazy loading?);  or because my internet connection improved (I changed WiFi connection, because my home internet is currently slow.)

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/screenshot-1584166949898674228.png?raw=true)

**Comment by matej-vavrek** [comment]
I have tried to select 15 compounds and it generated the dialog with link in less than 3 seconds:
https://fragalysis-matej.apps.xchem.diamond.ac.uk/viewer/react/snapshot/cb81901d-1088-4b2f-94e3-24cf8c255cca
It could be related to slower internet connection due to bigger payload.

**Comment by matej-vavrek** [comment]
Long shnapshot generation was not able to reproduce. It could be caused by current external circumstances.
