### ISSUE TITLE
piperidine-amides for MPro The aniline substitution seems especially potent.

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#191]
- Version: 0.2.2
- Name: Viromics
- Description: PCM-012781 ? 
PCM-0102972 ClCC(=O)N1CCC(CC1)C(=O)N2CCCCC2
PCM-0102974 CC(C)N(C)C(=O)C1CCN(CC1)C(=O)CCl

O=c1c(O)c(-c2ccc(O)cc2)oc2c(O)c(O)cc(O)c12

**Comment by phraenquex** [comment]
Very interesting data, but wrong place - we'll pick it up elsewhere.

**Comment by toniyol** [comment]
To all - do you have the email address of the submitter?
I transferred the smiles to the actual platform (https://covid.postera.ai/covid) but put my email address for now

**Comment by toniyol** [comment]
submission details - https://covid.postera.ai/covid/submissions/7b3d3065-7119-4dff-b3fd-df4d793955e8
