### ISSUE TITLE
[Report issue/Submit idea] Picture - screenshot overlaps buttons

### ISSUE THREAD

**Issue by veronikabelusikova** [m2ms/fragalysis-frontend#205]
Screenshot is too big - overlaps buttons below: 
![report issue](https://user-images.githubusercontent.com/60730965/77082039-d5a09480-69fb-11ea-9447-f461eb0f8bba.PNG)

**Comment by matej-vavrek** [comment]
This was resolved in #204 and some additional separate commits after.
