### ISSUE TITLE
Numbers that do not match a pre-defined filter should be coloured in pale red

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#207]
- Version: 0.3.0
- Name: Rachael Skyner
- Description: Currently they are white (examples circled). They should be a pale red colour like the swatch on the screenshot. (loving this submit idea filter, btw)

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/screenshot-1584708815524187837.png?raw=true)

**Comment by reskyner** [comment]
Hi guys, can we implement this one change before I push to production? (only if a quick fix)

Thanks!

**Comment by zemiacsik** [comment]
Sure, give me a moment please.

**Comment by matej-vavrek** [comment]
Sure, give me a moment please.

**Comment by matej-vavrek** [comment]
You may have a look at this on:
https://fragalysis-boris.apps.xchem.diamond.ac.uk/viewer/react/landing

**Comment by veronikabelusikova** [comment]
tested also on: 
https://fragalysis-boris.apps.xchem.diamond.ac.uk/viewer/react/snapshot/229118fd-c51a-4f3f-b781-d0c7be3a49a8

**Comment by reskyner** [comment]
Thanks guys! Awesome work
