### ISSUE TITLE
Remove status labels

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#208]
- Version: 0.3.1
- Name: Rachael
- Description: Remove the status labels (for now - until they are in the back-end/loader properly)

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/screenshot-1584910879173536154.png?raw=true)

**Comment by matej-vavrek** [comment]
Temporarily removed status labels:
https://fragalysis-matej.apps.xchem.diamond.ac.uk/viewer/react/landing

**Comment by veronikabelusikova** [comment]
tested on: 
https://fragalysis-matej.apps.xchem.diamond.ac.uk/viewer/react/snapshot/c1a777e2-ca87-480e-81fb-078899835876

**Comment by phraenquex** [comment]
Thanks - move to production
