### ISSUE TITLE
Don't alter the current view if a ligand is already displayed in the central protein veiwer

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#209]
- Version: 0.3.1
- Name: Rachael
- Description: If there is already a ligand turned on in the central protein viewer, don't alter the view in any way if a ligand in the same site is turned on. Leave the view the same. If a different site is selected, centre on the first ligand that is turned on in that site

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/screenshot-1584911028610133916.png?raw=true)

**Comment by veronikabelusikova** [comment]
tested on: 
https://fragalysis-tibor.apps.xchem.diamond.ac.uk/viewer/react/snapshot/d5343743-8dab-4725-a5b6-d1981eb57d9a

**Comment by phraenquex** [comment]
The view still jumps around when I turn on ligands.  Easy to test:  turn on the first ligand with A.  Then click on L for any other hit - the view zooms in and out every time.  
The spec said:  "Leave the view the same".  

Moving back to In Progress.

**Comment by matej-vavrek** [comment]
Could you please check this on this environment?

**Comment by phraenquex** [comment]
No, doesn't work - here's how to test:  
Load a ligand - zoom way out (scroll wheel) - load a different ligand - the view snaps straight back to the close zoom.  That is wrong - the view should change in no way at all - all that should happen is for a

**Comment by veronikabelusikova** [comment]
tested on: 
https://fragalysis-tibor.apps.xchem.diamond.ac.uk/viewer/react/snapshot/d1a269f3-7a86-4f80-9d63-27267ab74fe8

**Comment by reskyner** [comment]
The snapshot is broken, and the issue (from Franks comment) still exists on fragalysis.apps.xchem.diamond.ac.uk. Please create a new snaphot

**Comment by tibor-postek-m2ms** [comment]
https://fragalysis-boris.apps.xchem.diamond.ac.uk/viewer/react/snapshot/f71b2ace-d7be-4d0c-9d45-2664423da1e3

**Comment by reskyner** [comment]
This still doesn't work "Load a ligand - zoom way out (scroll wheel) - load a different ligand - the view snaps straight back to the close zoom. That is wrong - the view should change in no way at all - all that should happen is for a a few extra lines (the ligand) to show up on the screen. If anything else happens, then it's wrong."

I zoomed out in the central protein viewer, loaded a new compound from the left-hand side (L button) and then the zoom level reset again. There should be a setting in NGL viewer somewhere that stops the automatic zooming on loading a new object.

**Comment by phraenquex** [comment]
So the "don't reposition" does sometimes happen - e.g. on that snapshot, turn on site 5 - then it jumps to site 5.  Then turn on a site 3 ligand - then it doesn't jump to site 3. 
Unfortunately, this is not really what the ticket is trying to indicate.
Rachael, probably you must set up (urgently?) a zoom session to demionstrate exactly what's happening and what's required.

**Comment by tibor-postek-m2ms** [comment]
please test the newest session https://fragalysis-boris.apps.xchem.diamond.ac.uk/viewer/react/fragglebox/1fb9ebf8-30c2-48e5-b208-7200c9d8b894

**Comment by phraenquex** [comment]
Fantastic - this is SO much better...  its like a completely different interface!!!   MASSIVE RELIEF. 
Please push to production ASAP.

**Comment by phraenquex** [comment]
Moved to "issue pull request" swimlane.
