### ISSUE TITLE
Typing into "Report issue" dialogue is terribly slow - at least 300ms / keystroke

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#210]
- Version: 0.3.1
- Name: Frank von Delft
- Description: Seems to have been introduced by the sketch tool.
  On both firefox and chrome.

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/screenshot-1584919559730579687.png?raw=true)

**Comment by phraenquex** [comment]
I tested:  it's definitely the sketch function that slows it down.  Without a screenshot, there is no typing lag.  Consider it a bug.

**Comment by matej-vavrek** [comment]
Delay was reduced:

**Comment by phraenquex** [comment]
No, this is still exactly as broken as before - it's almost impossible to type.  I'm using firefox.

**Comment by phraenquex** [comment]
"Delay was reduced" - there ought to be no delay at all - it feels like some rendering issue, as if every keystroke triggers redrawing of the screenshot or something daft like that.

**Comment by tibor-postek-m2ms** [comment]
you can test it at https://fragalysis-matej.apps.xchem.diamond.ac.uk/viewer/react/landing v.6.0.2
