### ISSUE TITLE
Make it possible to resize the "Report issue" dialogue.

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#211]
- Version: 0.3.1
- Name: Frank von Delft
- Description: Especially when there's a screenshot, it's really rubbish not to see more of it.

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/screenshot-1584919642861706296.png?raw=true)

**Comment by matej-vavrek** [comment]
Added possibility to resize the report window:
https://fragalysis-matej.apps.xchem.diamond.ac.uk/viewer/react/landing

**Comment by veronikabelusikova** [comment]
tested on: 

https://fragalysis-matej.apps.xchem.diamond.ac.uk/viewer/react/snapshot/4ba57ed5-4685-45c2-bda2-347b0a2020ee

**Comment by phraenquex** [comment]
Great thanks! Moving to next swimlane - please put in production.

(The lagtime for typing when a screenshot is included is stll there and very very disabling.  But a different tickedt, I think.)

**Comment by matej-vavrek** [comment]
Yes, the lagtime is #210, it is caused by validation and re-rendering of form. It is under more investigation.

**Comment by phraenquex** [comment]
Please do move to production!
