### ISSUE TITLE
There should be a button 'S' in the display toggles set that turns on the surface for the protein of the current structure, with the default as shown

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#214]
- Version: 0.3.1
- Name: Rachael
- Description: Surface: electrostatic, covalent radius, not including the water or ligand

This is implemented by Matteo Ferla (matteo@well.ox.ac.uk) on his website michelNGLO:

code: https://github.com/matteoferla/MichelaNGLo-app

You can email him directly for help

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/screenshot-1584923260800515353.png?raw=true)

**Comment by boriskovar-m2ms** [comment]
Is this surface different from surface you can turn on in display settings -> protein -> (?view mode?) -> switch from cartoon to surface mode/view/representation

**Comment by matteoferla** [comment]
The selection of the surface set to `polymer` results in the waters (the red oxygen atoms) and any ligands within the same object (NGL scene component) to be outside of the protein surface.

                component.addRepresentation("surface", {
                                                            sele: 'polymer',
                                                            colorScheme: color,
                                                            colorDomain: [-0.3, 0.3],
                                                            surfaceType: "av"
                                                        });

**Comment by matej-vavrek** [comment]
Thank you @matteoferla!

#228 solves this.
