### ISSUE TITLE
Potential hybrid

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#220]
- Version: 0.4.0
- Name: Mark Honey
- Description: This design aims to create a hybrid of the non-covenant binders to the active site based on the fragments shown. The new compound aims to pick up the main interactions of these fragments.

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/screenshot-1585263239667426930.png?raw=true)

**Comment by phraenquex** [comment]
Closing - user mis-understood the "Idea" dialogue.
