### ISSUE TITLE
Fix what is shown on FIRST loading a target

### ISSUE THREAD

**Issue by phraenquex** [m2ms/fragalysis-frontend#227]
(I remember creating a ticket about this - but can't find it now, and it still isn't fixed.)

The very first time one loads a target (by clicking on the landing page), what needs to happen:

- Tunr on (check) the first site in the site list
- Turn on the _complex_ of the first ligand of the site
- Turn on _every_ ligand of the site
- Set the "clip near" value of the NGL viewer to 42
- Set the "fog far" value of the NGL viewer to 62
- Set the background coour of the NGL viewer to black
- Zoom out (about 2x demagnification) from whatever value it currently calculates

Do this ONLY on the first load of the target.

This is a SUPER QUICK win - please prioritise, it's long overdue.

**Comment by reskyner** [comment]
@phraenquex these 3:
Tunr on (check) the first site in the site list
Turn on the complex of the first ligand of the site
Turn on every ligand of the site

We had on at some point, but they were _very, very_ slow. That was just for one molecule. We will implement anyway and test – might need a rethink.

**Comment by phraenquex** [comment]
What you display for all is crucial:  ONLY the ligand - that ought not to be slow, at least, it's not a lot of data.
Ideal behaviour:  lazy loading
Compromise:  show protein and ligand for the first hit.

**Comment by matej-vavrek** [comment]
- [ ] Tunr on (check) the first site in the site list
- [ ] Turn on the complex of the first ligand of the site
- [ ] Turn on every ligand of the site
- [ ] Set the "clip near" value of the NGL viewer to 42
- [ ] Set the "fog far" value of the NGL viewer to 62
- [ ] Set the background coour of the NGL viewer to black
- [ ] Zoom out (about 2x demagnification) from whatever value it currently calculates

Zoom was changed, but I did not notice any difference.. (this will be further analysed)

Preview is available here:
https://fragalysis-matej.apps.xchem.diamond.ac.uk/viewer/react/landing

**Comment by phraenquex** [comment]
Great.
The fog far and clip near parameters are not being applied by the NGL viewer;  the sliders are correct, but one must click on them to have the NGL viewer respond.  You're probably missing some kind of trigger call.

**Comment by phraenquex** [comment]
on first load, the progress bar and hourglass cursor should show up immediately; currently, there is quite a lot that happens before they come on, which is pretty confusing. (Lower priority)

    on first load, the "Clip near" and "Fog far" settings are NOT propagated to the NGL viewer, only to the sliders in Settings controls. Which means, the thing that matters (the 3D view) effectively still retains the bug that #227 was meant to fix.

**Comment by phraenquex** [comment]
On first load, the progress bar and hourglass cursor should show up immediately; currently, there is quite a lot that happens before they come on, which is pretty confusing. (Lower priority)

On first load, the "Clip near" and "Fog far" settings are NOT propagated to the NGL viewer, only to the sliders in Settings controls. Which means, the thing that matters (the 3D view) effectively still retains the bug that #227 was meant to fix.

**Comment by phraenquex** [comment]
This is perfect now!  Please move to production immediately;  I'm putting it in that swimlane.
