### ISSUE TITLE
Additional display toggles in hit navigator: contacts, surface, electron density

### ISSUE THREAD

**Issue by phraenquex** [m2ms/fragalysis-frontend#228]
(Again, I'm pretty sure I created a ticket on this topic a few weeks ago - again can't find it.)

We need additional display toggle buttons alongside the existing four.  They should be, in this order and with these letters:

- A --> turn on everything
- L --> (for "ligand"):  turn on the ligand
- P --> (for "protein"):  turn on only the _lines_ of what's now called "complex"
- C --> (for "contacts"):  turn on the dotted lines of what's currently called "complex"
- S --> (for "surface"):  turn on the surface of _only_ the protein.  
- D --> (for "density"):  turn on the electron density evidence
- V --> (for "vectors"):  turn on the vectors 

Two things:  splitting the current "C" (complex) into P and C will apparently require loading things differently (says Rachael) - well, then just do it, because it will also allow S to be rendered correctly.  (Rachael will need to talk you through this in detail.)

This is URGENT now, sorry... has bubbled up from several comments of people using for serious work.  So I'm going to mark it as "urgent fix".  Looking at the swim-lanes, it's definitely more important than the other things in progress (except for #227, if that is as super simple as I think it is).

**Comment by phraenquex** [comment]
Issue #214  is relevant to this issue;  and resolving this one will close #214.

**Comment by phraenquex** [comment]
Two of the toggles, C and D, might be difficult to do quickly:  in that case, just grey them out.

Later:  for D, make it so that it allows for the backend to return no data - in which case, just grey it out.

**Comment by reskyner** [comment]
P --> (for "protein"): turn on only the lines of what's now called "complex"
C --> (for "contacts"): turn on the dotted lines of what's currently called "complex"

separate out contacts and lines - check the display controls for the current 'complex implementation' and split the two representations out. Lines -> P and contacts -> C

**Comment by reskyner** [comment]
S --> (for "surface"): turn on the surface of only the protein.

surface radiusType = covalent; colourScheme = electrostatic

Should be the protein (same object as the lines from above) for the ligand we're clicking the S button for. 

Make sure not to include ligand and waters in the surface. (#214 )

**Comment by reskyner** [comment]
D --> (for "density"): turn on the electron density evidence
 Needs implementing on Back-end. Rachael to do this ASAP

**Comment by phraenquex** [comment]
No, Density is not part of the urgent spec.  Just make front-end recognise whether it's available, and if not, show the button greyed-out.
And if there's back-end work to do, my **strong** preference is for M2M to do it.

**Comment by matej-vavrek** [comment]
- [ ] A --> turn on everything
- [ ] L --> (for "ligand"): turn on the ligand
- [ ] P --> (for "protein"): turn on only the lines of what's now called "complex"
- [ ] C --> (for "contacts"): turn on the dotted lines of what's currently called "complex"
- [ ] S --> (for "surface"): turn on the surface of only the protein.
- [ ] D --> (for "density"): turn on the electron density evidence
- [ ] V --> (for "vectors"): turn on the vectors

Preview should be always available here:
https://fragalysis-matej.apps.xchem.diamond.ac.uk/viewer/react/landing

**Comment by matej-vavrek** [comment]
"most important, for this selection we should be using by vDW for radius type"
Settings adjusted to this snapshot (could become unavailable), but basicallychanged "radiusType: vdw, opacity: 0.47":
https://fragalysis-matej.apps.xchem.diamond.ac.uk/viewer/react/snapshot/2584b52d-c15c-4256-9abe-99a6f305c37d

**Comment by reskyner** [comment]
Excellent! Can you open PR for the surface?

**Comment by phraenquex** [comment]
A few things to fix on Display Controls, which are related to this ticket: 

- in the "Display controls" dialog, everything is named very usefully (Mpro-x0072_0_surface) - except the ligands.  Can they be named *_ligand, please.

- And sort all Display Controls objects alphabetically (rather than the order in which they were added)

**Comment by phraenquex** [comment]
Also:  we need  a toggle on the left side to turn off the cartoon.  I suggest something like:  a toggle to the right of the overall toggles named "R" (tooltip: ribbon).  Leave a little space between the overall [V] and [R] toggles.  (But anything else that you feel make sense is fine by me.)

The problem is that "Dispaly controls" is not very noticeable, so many people are unlikely to use it.

**Comment by phraenquex** [comment]
Last bug:  the electrostatic surface is not coming up with the right colour.  It's not a blocker, but should be looked at urgently.  Do create a new ticket if it turns out to be a Big Bug.
