### ISSUE TITLE
Display toggles that turn on/off things for all hits at once 

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#229]
- Version: 0.5.1
- Name: Frank von Delft
- Description: See the scribles on the screenshot:  Clicking those must turn on (or off) the relevant toggle for *all* the hits currently shown in the hit navigator.

For turning off, it should turn off *everything* whether or not it's shown in the hit navigator.

Complements #228 - so need those additional toggles here too, of course.

(Apologies the typos....)

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/screenshot-1585717405010800086.png?raw=true)

**Comment by phraenquex** [comment]
Adding to "in progress" swimlane - need this week if possible.

**Comment by matej-vavrek** [comment]
Preview of this can be found here:
https://fragalysis-matej.apps.xchem.diamond.ac.uk/viewer/react/landing

**Comment by matej-vavrek** [comment]
- [ ] Work with whole hit list, not just visible ones.

**Comment by phraenquex** [comment]
This is fantastic!!!

**Comment by phraenquex** [comment]
This is fantastic!!!
