### ISSUE TITLE
Turning on all proteins and then turning off the site leaves the proteins in the central viewer with no way to turn them off

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#236]
- Version: 0.5.1
- Name: Rachael via Frank
- Description: If I turn on a few of the (P)roteins in one site;  then turn on another site;  then unselect all (P)rotein with the overall toggle - the (P)roteins of the original site don't turn off.  The only way to turn them off is to reactivate the original site, and then toggle them off.

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/screenshot-1585862440014805297.png?raw=true)

**Comment by matej-vavrek** [comment]
- [ ] Clear all selected proteins when turning off site

**Comment by matej-vavrek** [comment]
Fixed:
https://fragalysis-matej.apps.xchem.diamond.ac.uk/viewer/react/landing

**Comment by phraenquex** [comment]
This is definitely fixed now - fantastic!  Please move to production ASAP - I'll move it to that swimlane.
