### ISSUE TITLE
Overall display toggles - further bug

### ISSUE THREAD

**Issue by phraenquex** [m2ms/fragalysis-frontend#239]
Follows on from #229 - only marked "urgent" because it's a bug-fix for an almost-complete feature.

if you have (P)rotein displayed for any hits in one site, then unselect that site, the (P)rotein remains displayed, it's meant to go away. (The (L)igands do go away, good).  The (P) remains displayed, even if you turn off the overall (P)rotein toggle
29

**Comment by matej-vavrek** [comment]
#236 resolves this
