### ISSUE TITLE
Set default assembly to BU1 for proteins

### ISSUE THREAD

**Issue by reskyner** [m2ms/fragalysis-frontend#240]
for example:
```
stage.loadFile("data://1IHM.pdb", {
  defaultAssembly: "BU1"
})
```

should give us something like this for Mpro:
![image](https://user-images.githubusercontent.com/12764941/78366358-4b8a2b80-75b8-11ea-82a7-42ebab8aeea0.png)

instead of this:
![image](https://user-images.githubusercontent.com/12764941/78366923-2ba73780-75b9-11ea-93f6-d04e98b17c96.png)

**Comment by reskyner** [comment]
(should be used for anything that is a protein and not a ligand, so the template protein surface, protein, and interactions)

**Comment by reskyner** [comment]
currently: `stage.loadFile(input_dict.prot_url, { ext: 'pdb'})`
should be: `stage.loadFile(input_dict.prot_url, { ext: 'pdb' ,  defaultAssembly: "BU1"})`

As far as I can tell.

**Comment by matej-vavrek** [comment]
It could be tested on:
https://fragalysis-matej.apps.xchem.diamond.ac.uk/viewer/react/landing
Also it is part of xchem/fragalysis-frontend#159 PR
