### ISSUE TITLE
Electrostatic surfac colours are wrong (all blue)

### ISSUE THREAD

**Issue by phraenquex** [m2ms/fragalysis-frontend#241]
The electrostatic surface (#228) is not coming up with the right colour. It's all blue, when it should be red-white-blue.  
It might be something in the PDB file, e.g. incorrect protonation state defined on upload, or similiar.  Might need some expert (e.g. Matteo Ferla) to troubleshoot.

**Comment by matej-vavrek** [comment]
It could be cause by "colorDomain: [-0.3, 0.3]" setting*, because without this it looks different.

Settings for surface would be then like
```
{
  sele: 'polymer',
  colorScheme: 'electrostatic',
  // colorDomain: [-0.3, 0.3],
  surfaceType: 'av',
  radiusType: 'vdw',
  opacity: 0.47,
  colorValue: colour
}
```

\* https://github.com/m2ms/fragalysis-frontend/issues/214#issuecomment-603433002

**Comment by matej-vavrek** [comment]
It was caused by rendering of surface. Fixed version:
https://fragalysis-matej.apps.xchem.diamond.ac.uk/viewer/react/landing

**Comment by phraenquex** [comment]
Great!  
So two details that now become clear:
1) opacity should be 0.74;  
2) line thickness of the protein should be higher (4 or 5)  - so that it's visible enough through the surface.
[ 3) I can't edit the display settings of the *_protein object in the Display Controls]

**Comment by matej-vavrek** [comment]
Thank you for the feedback.
- [ ] opacity should be 0.74;
- [ ] line thickness of the protein should be higher (4 or 5) - so that it's visible enough through the surface.
- [ ] ~I can't edit the display settings of the *_protein object in the Display Controls]~ objects loaded on first target entry is not possible to edit

**Comment by matej-vavrek** [comment]
Fixed and ready:
https://fragalysis-matej.apps.xchem.diamond.ac.uk/viewer/react/landing

**Comment by matej-vavrek** [comment]
Like these?
![image](https://user-images.githubusercontent.com/60509086/78612565-f2492300-7869-11ea-8956-8bc57562fd9a.png)

**Comment by phraenquex** [comment]
Okay, starting a new ticket - this one is sorted, please issue pull request.
