### ISSUE TITLE
Tidy up "Display Controls" dialog:  rename ligands to *_ligand, sort alphabetically

### ISSUE THREAD

**Issue by phraenquex** [m2ms/fragalysis-frontend#242]
A few things to fix on Display Controls dialog

- in the "Display controls" dialog, everything is named very usefully (Mpro-x0072_0_surface) - except the ligands. Can they be named *_ligand, please.

- sort all objects alphabetically (rather than the order in which they were added)

- check that the icons don't misalign when the vertical scroll bar appears, when the list of objects is longer than fit on the screen

- reduce the font size and distance between lines, so that more of them fit on a normal screen.

**Comment by matej-vavrek** [comment]
![image](https://user-images.githubusercontent.com/60509086/78651991-6367f500-78c1-11ea-819d-4b161a2da125.png)

So the ligand would be renamed from "MOLECULE_20622_LIGAND" to "NUDT5A-x0114_4_LIGAND", right or it could stay as "MOLECULE_20622_LIGAND"?

20622 is id of hit
NUDT5A-x0114_4 is protein code

![image](https://user-images.githubusercontent.com/60509086/78654781-5c42e600-78c5-11ea-90f5-0553437aa564.png)

**Comment by phraenquex** [comment]
Can this be fixed urgently?  I've finally realised the bug makes it really difficult to understand the data, because that meaningless label is also what shows up when you hover the mouse over the NGL viewer, and then you can never figure out what to turn on/off.

To answer Matej's question:  yes, the ligand would be renamed from "MOLECULE_20622_LIGAND" to "NUDT5A-x0114_4_LIGAND".

**Comment by phraenquex** [comment]
I've moved it top of the in-progress swim-lane.

**Comment by tibor-postek-m2ms** [comment]
https://github.com/xchem/fragalysis-frontend/pull/178/

**Comment by tibor-postek-m2ms** [comment]
![image](https://user-images.githubusercontent.com/57392303/82193623-ebe0a900-98f5-11ea-844e-671c1a74641e.png)

**Comment by phraenquex** [comment]
Great!  Please pull to production...
