### ISSUE TITLE
Waters not being rendered with new surfaces and display toggles (Mpro?)

### ISSUE THREAD

**Issue by phraenquex** [m2ms/fragalysis-frontend#245]
The waters for Mpro are not currently rendering (though they are for EFP***).

I suspect this is to do with the selection statement for what's protein and what's ligand.  Waters should be rendered with the *_protein object, but the surface should be rendered over only the protein atoms (and not the waters).

I don't know if this breaks lots of things...  putting it top of "in progress", because really it's a follow-on from #228.

**Comment by matej-vavrek** [comment]
It looks that some .pdo files do include information about the water for rendering and some do not. So the rendering method was changed to always include also .sdf files which seem to have it too.
