### ISSUE TITLE
Bugs when first entering a target

### ISSUE THREAD

**Issue by phraenquex** [m2ms/fragalysis-frontend#246]
when one first enters a target (Mpro):

- it does not zoom in on site 1 - it stays zoomed out at some random angle

- the hourglass cursor (and progress bar) only comes on very late in the loading process.  

These are further fixes to #227.  Might also be consequence of the BU1 ticket (#240).

**Comment by matej-vavrek** [comment]
Preview of fixed not zooming in can be foun here:
https://fragalysis-matej.apps.xchem.diamond.ac.uk/viewer/react/landing

Loading inconsistency moved into a separate task #253

**Comment by phraenquex** [comment]
Looks great thank you!!  @reskyner, please pull to production asap.
