### ISSUE TITLE
Clear selection and NGL interactions

### ISSUE THREAD

**Issue by boriskovar-m2ms** [m2ms/fragalysis-frontend#250]
After pressing clear selection button:
- [x]  clear all selected sites in small NGL site preview
- [x] small NGL site preview should retain its default look i.e. all properties shall remain constant at all times

**Comment by tibor-postek-m2ms** [comment]
- [ ] Fix the order - the first load mol groups and protein and then it can be selected first mol group and all ligands. The current state is, that when mol groups are loaded then select the first. This cause, that sbnapshot data containts molecule group selection.

**Comment by tibor-postek-m2ms** [comment]
https://github.com/xchem/fragalysis-frontend/pull/170
