### ISSUE TITLE
Selection toggles improvements

### ISSUE THREAD

**Issue by boriskovar-m2ms** [m2ms/fragalysis-frontend#251]
Mass selection toggles should consist only from L, P and C buttons
For individual molecule the A toggle button should control only L, P and C buttons

**Comment by tibor-postek-m2ms** [comment]
https://fragalysis-boris.apps.xchem.diamond.ac.uk/viewer/react/landing

**Comment by tibor-postek-m2ms** [comment]
you can test at https://fragalysis-tibor.apps.xchem.diamond.ac.uk/viewer/react/landing

**Comment by tibor-postek-m2ms** [comment]
https://github.com/xchem/fragalysis-frontend/pull/169
