### ISSUE TITLE
Loading inconsistency

### ISSUE THREAD

**Issue by matej-vavrek** [m2ms/fragalysis-frontend#253]
- the hourglass cursor (and progress bar) only comes on very late in the loading process.

Loading of hits on target entry should be right after first site is selected. Currently there is a delay.

**Comment by boriskovar-m2ms** [comment]
Several buttons are active too and they need to be disabled

**Comment by tibor-postek-m2ms** [comment]
to solve this issue please read following link https://reactjs.org/docs/concurrent-mode-patterns.html
