### ISSUE TITLE
[Share snapshot from project] When I click different share buttons, same snapshot is shared allways

### ISSUE THREAD

**Issue by veronikabelusikova** [m2ms/fragalysis-frontend#255]
1. open project history
2. click on the share button next to selected snapshot - selected snapshot is shared
3. click on the share button next to the other snapshot - selected snapshot is shared again - bug

**Comment by tibor-postek-m2ms** [comment]
- [ ] fix in nglReducers countOfPendingNglObjects

**Comment by tibor-postek-m2ms** [comment]
- [ ] fix creating of initial snapshot

**Comment by tibor-postek-m2ms** [comment]
- [ ] open target and save snapshot (create project, save snapshot) and project has problem with NGL viewer 
![image](https://user-images.githubusercontent.com/57392303/79536269-ef2b0f80-807f-11ea-9649-42091ae9f5c5.png)
