### ISSUE TITLE
Selected compounds tab - Show cross reference for compound

### ISSUE THREAD

**Issue by boriskovar-m2ms** [m2ms/fragalysis-frontend#274]
There will be added X display toggle. This toggle will display modal window where same compound from all datasets will be displayed with relevant scores. Backend will provide API function to retrieve scores of the compound from all defined datasets.
You can select only one X button in same time.

Hint:
find identical **name** of compounds in datasets e.g. `HAN-NEW-5F56C3BC-4`

Buttons: 
Checkbox, A, L, P, C, S

- [x] add X button to each compound in every dataset tab

- [x] fix showing title of compounds in inspiration dialog

- [x] auto hide cross reference dialog like inspiration dialog (after scroll)

**Comment by teriraj** [comment]
Click to X toggle - the window is opened
Click to another tab - the modal window changes its position - it was jumped to left corner of site.  
Video: https://www.loom.com/share/64bad28176b148e59d88505752438662
