### ISSUE TITLE
Redirecting of the legacy snapshots

### ISSUE THREAD

**Issue by boriskovar-m2ms** [m2ms/fragalysis-frontend#277]
Every snapshot or session is saved state of the UI which is handled by Redux. Problem that these states are now not compatible. 
All the snapshots that were shared on the social media or websites and general scientific community would be created from scratch. We would extend the snapshot table by adding a new column which would contain the hash key which identifies the session/snapshot (id string in the URL). So we would assign hash keys of the original snapshots to their newly recreated counterparts. Then we will add something like URL translation to the backend which will work in the way that when we detect a hash key in the url we would look into the database if we can find matching snapshot and if matching snapshot is found then the user is redirected to the new recreation of the snapshot.

**Comment by tibor-postek-m2ms** [comment]
https://fragalysis-tibor.apps.xchem.diamond.ac.uk/viewer/react/sessions/5207709d-2b2a-4db9-af99-44ecf1726674
https://fragalysis-tibor.apps.xchem.diamond.ac.uk/viewer/react/sessions/5207709d-2b2a-4db9-af99-44ecf1726675
