### ISSUE TITLE
Create project from snapshot - filtering

### ISSUE THREAD

**Issue by boriskovar-m2ms** [m2ms/fragalysis-frontend#278]
Only snapshots which have project and are owned by the logged in user can be used for creation of the new project.

**Comment by tibor-postek-m2ms** [comment]
- [ ] install and use https://github.com/philipn/django-rest-framework-filters#automatic-filter-negationexclusion

**Comment by phraenquex** [comment]
Please clarify what was implemented or fixed here.  The ticket as written does not make whether this is the _desired_ behaviour, or whether it's considered a bug.

What is needed:  anybody that's logged in should be able to start a project from any snapshot.
