### ISSUE TITLE
[Application] Project creating from snapshot from anonymous user 

### ISSUE THREAD

**Issue by veronikabelusikova** [m2ms/fragalysis-frontend#282]
1) I create snapshot as anonymous (logged out) user
2) login --> snapshot is opened, project history is displayed and also I can click "Save" button 

--> from shared snapshot from anonymous user I should not do anything, only see snapshot details

**Comment by tibor-postek-m2ms** [comment]
- [ ] disable save button if project has no author

- [ ] hide project history view if project has no author
