### ISSUE TITLE
[Application] Parts of molecules are automatically added (selected) to snapshot from anonymous user

### ISSUE THREAD

**Issue by veronikabelusikova** [m2ms/fragalysis-frontend#283]
1) As anonymous user I create snapshot - some parts of molecules are selected: 
![site 11](https://user-images.githubusercontent.com/60730965/80180404-f8c5f180-8602-11ea-8482-00d23f505c3d.PNG)

2) Click on Save button --> snapshot is created, but some selected parts of molecules are added: 
![site 11a](https://user-images.githubusercontent.com/60730965/80180410-fc597880-8602-11ea-9b0b-2a2e17c447f7.PNG)

3) Open this session from link (logged in or not, does not matter) --> new selected parts are still displayed. 
4) Log in --> Create project from snapshot: selected parts are selected correctly, just like I have select them.

**Comment by veronikabelusikova** [comment]
Same behaviour when: 
1) as anonymous user I open existing project
2) click on Save button --> new snapshot is created, but some selected parts are "added"

**Comment by tibor-postek-m2ms** [comment]
- [ ] anonymous user cant save projects only targets
