### ISSUE TITLE
[Hit cluster selector] Error after "clear selection" button is clicked, but no site is selected

### ISSUE THREAD

**Issue by veronikabelusikova** [m2ms/fragalysis-frontend#286]
1. project is opened, no site is selected
2. click on Clear selection
3. error is displayed
4. click Close in error message
5. all parts are white: 
![image](https://user-images.githubusercontent.com/60730965/80477621-8b8cc600-894c-11ea-8966-d46e656b8f3a.png)

**Comment by tibor-postek-m2ms** [comment]
https://github.com/xchem/fragalysis-frontend/pull/171
