### ISSUE TITLE
[Report issue/Submit idea] Error - status code 422 when sending issue/idea

### ISSUE THREAD

**Issue by veronikabelusikova** [m2ms/fragalysis-frontend#288]
When I want to create issue or idea, Error message is displayed after issue/ide creating. 
![image](https://user-images.githubusercontent.com/60730965/80576478-8ccdf980-8a05-11ea-8e0c-a6bf34b84938.png)

Same behaviour for report issue and submit idea. 

This happens only when screenshot is created. 

When screenshot is not created, button for confirm and send issue it is possible to click, but without any reaction.

**Comment by tibor-postek-m2ms** [comment]
resolved here https://github.com/m2ms/fragalysis-frontend/issues/323
