### ISSUE TITLE
[Hit navigator] Incorrect functionality of buttons

### ISSUE THREAD

**Issue by veronikabelusikova** [m2ms/fragalysis-frontend#290]
- [x] Hide all button: when I click on this button, all molecules parts except P - sidechains and S - surface are hidden - all parts should be hidden - bug. Sidechains and Surface stay selected in Hit navigator and also they are displayed in NGL viewer. 

- [x] L, P. C buttons for mass molecules management should be "medium blue", when f. e. "L" only in few molecules is selected, currently they are dark blue when all or only few are selected. 

- [x] "A" button for single molecules does not work when S in that molecule is selected.

**Comment by veronikabelusikova** [comment]
- [ ]  Hide all button: when I click on this button, all molecules parts except P - sidechains and S - surface are hidden - all parts should be hidden - bug. Sidechains and Surface stay selected in Hit navigator and also they are displayed in NGL viewer.

- [ ]  L, P. C buttons for mass molecules management should be "medium blue", when f. e. "L" only in few molecules is selected, currently they are dark blue when all or only few are selected.

- [ ]  "A" button for single molecules does not work when S in that molecule is selected.

**Comment by tibor-postek-m2ms** [comment]
https://github.com/xchem/fragalysis-frontend/pull/174
