### ISSUE TITLE
Invalid snapshot notification

### ISSUE THREAD

**Issue by boriskovar-m2ms** [m2ms/fragalysis-frontend#291]
If someone access the shared link to the old snapshot and new remapping to new snapshot within projects is not created then the user should be notified. 
There are two cases:
1. snapshot exists: User shall be notified with message: "Snapshot is expired"
2. snapshot doesn't exist: User shall be notified with message: "Snapshot doesn't exist"

**Comment by veronikabelusikova** [comment]
I was able to test only second situation - not existing snapshot. It works correctly, with message: 
"Session is not found".

**Comment by phraenquex** [comment]
Please figure out how to test scenario 1 too, before moving to "Tested". 
@tibor-postek-m2ms , maybe you can generate some old session URLs and pass them over to Veronika for testing;  paste them here so I can check too.
