### ISSUE TITLE
Share button behaviour

### ISSUE THREAD

**Issue by boriskovar-m2ms** [m2ms/fragalysis-frontend#292]
Share button should behave in following way:
When user presses the Share button the new snapshot should be created and the link to the newly created snapshot should be shown in the modal window. This should work for anonymous and signed in user. Still applies that anonymous user can created snapshot only from target and only and only owner of the project/snapshot is able to create a new snapshot from given snapshot

**Comment by veronikabelusikova** [comment]
bugs: in already existing project: 
logged in user: after making some changes I want to share --> new snapshot is not created and last saved snapshot is shared
anonymous user with direct link to project --> only snapshot is shared, but when make some changes and want to share them - snapshot is not created, only original shared snapshot is shared again

when creating new project by Share button: 
1) open target
2) make some changes
3) click the Share button
4) projekt and also first snapshot created correctly, shared snapshot is correct
--> but page is not loaded again and still only snapshot info is displayed (it should refresh and display also project history)
--> project is created correctly, it is in project list and in shared tab also project history is displayed, only refresh is missing

**Comment by tibor-postek-m2ms** [comment]
https://github.com/xchem/fragalysis-frontend/pull/172
