### ISSUE TITLE
When sharing from anonymous snapshot with login, project ID is not changed

### ISSUE THREAD

**Issue by veronikabelusikova** [m2ms/fragalysis-frontend#295]
As a logged in user with link to anonymous snapshot. 

1) make changes
2) share snapshot --> dialog is opened
3) create new snapshot and share
4) ID of project of new snapshot is the same as ID pf project of anonymous snapshot - bug, ID should be different (new)

**Comment by tibor-postek-m2ms** [comment]
Depends on #292

**Comment by tibor-postek-m2ms** [comment]
https://github.com/xchem/fragalysis-frontend/pull/175
