### ISSUE TITLE
Report issue dialog

### ISSUE THREAD

**Issue by tibor-postek-m2ms** [m2ms/fragalysis-frontend#323]
Report issue does not work.

issue without screenshot - Report button does nothing
issue with screenshot - screenshot is not correctly displayed in window, when I click report button, error is displayed

same bahaviour for Submit idea

**Comment by tibor-postek-m2ms** [comment]
Documentation How to create issues https://developer.github.com/v3/issues/#create-an-issue

![image](https://user-images.githubusercontent.com/57392303/83849971-87ed1b80-a710-11ea-963a-cb771b7c13c1.png)
There is problem with structure of sending data

**Comment by teriraj** [comment]
- [ ] issue without screenshot - Report button does nothing
- [ ] issue with screenshot - screenshot is not correctly displayed in window, when I click report button, error is displayed

**Comment by teriraj** [comment]
Issue without screenshot - after click to "report issue"button or "submit idea" button - endless loading - and the bug is not reported in Github.

**Comment by teriraj** [comment]
The problem is not solved: 
Issue without screenshot - after click to "report issue"button or "submit idea" button - endless loading - and the bug is not reported in Github. 
There is another bug about reports:
https://github.com/m2ms/fragalysis-frontend/issues/379
