### ISSUE TITLE
Broken snapshot

### ISSUE THREAD

**Issue by boriskovar-m2ms** [m2ms/fragalysis-frontend#338]
When trying to access snapshot https://fragalysis.diamond.ac.uk/viewer/react/projects/2/6 following error is displayed:

![image](https://user-images.githubusercontent.com/16878338/83487721-d352c000-a4ab-11ea-857b-effa99d4653a.png)

**Comment by tibor-postek-m2ms** [comment]
Before loading objects into NGL View, it was called this command `console.log(target.OBJECT_TYPE, target);`
![image](https://user-images.githubusercontent.com/57392303/83503675-b9bd7280-a4c3-11ea-9cae-e86db9d7b07d.png)

It was make a change replacing object type PROTEIN to HIT_PROTEIN

- [ ] fix this change (e.g if OBJECT_TYPE is undefined and name contains word PROTEIN, replace it by HIT_PROTEIN)

**Comment by tibor-postek-m2ms** [comment]
There is issue, that https://fragalysis-tibor.apps.xchem.diamond.ac.uk/viewer/react/projects/2/6 and https://fragalysis-tibor.apps.xchem.diamond.ac.uk/viewer/react/preview/target/Mpro has another mol group list and molecule list of given mol group too. It is required to make snapshots of database too, or something else with same behaviour. Every time, when you select something, it calls backend with 404 data not found (befause snapshot is old and data were removed)
