### ISSUE TITLE
Test report issue dialog

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#348]
- Version: 0.8.7
- Name: Test report
- Email: pavol.brunclik@m2ms.sk
- Description: Test report issue dialog

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/screenshot-15916177374237076.png?raw=true)

**Comment by teriraj** [comment]
The task is opened only for testing report , it can be closed.
