### ISSUE TITLE
Report test only - it can be closed

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#349]
- Version: 0.8.7
- Name: Report test only - it can be closed
- Email: pavol.brunclik@m2ms.sk
- Description: Report test only - it can be closed

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/screenshot-1591618290457786377.png?raw=true)

**Comment by teriraj** [comment]
The task is opened only for testing report , it can be closed.
