### ISSUE TITLE
Can't share snapshot when a vector is selected

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#365]
- Version: 0.8.7
- Name: Rachael
- Email: rachael.skyner@diamond.ac.uk
- Description: 1. Turn on vectors
2. Press share
3. Nothing happens

There is an error displayed in the console
- Reducers: https://github.com/m2ms/fragalysis-assets/blob/master/Reducers-1592333175447291786.json?raw=false

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/Screenshot-1592333172722586825.png?raw=true)

**Comment by tibor-postek-m2ms** [comment]
![image](https://user-images.githubusercontent.com/57392303/84860507-6f192a00-b06f-11ea-8c02-ff094a863a2d.png)

- [ ] increase client_max_body_size in NGiNX of stack
