### ISSUE TITLE
Include site number in the Fragments modal

### ISSUE THREAD

**Issue by reskyner** [m2ms/fragalysis-frontend#368]
Include site number in the Fragments modal:

![image](https://user-images.githubusercontent.com/12764941/84872571-f79cc800-b079-11ea-87bc-4a374e61131a.png)

**Comment by tibor-postek-m2ms** [comment]
use follow endpoint `http://localhost:8080/api/molgroup/?mol_id=30`

**Comment by teriraj** [comment]
site number is displayed incorrectly (NaN)
![2020-06-19_13h27_39](https://user-images.githubusercontent.com/65952633/85127937-a84cc800-b230-11ea-88f7-259a5cf186f2.png)
