### ISSUE TITLE
Report issue - it is reported as idea

### ISSUE THREAD

**Issue by teriraj** [m2ms/fragalysis-frontend#379]
1. Use button "Report issue"
2. Dialog window is opened, but for "Submit idea".
3. When I save the dialog window, it is saved as idea, no report issue. 

Video: https://www.loom.com/share/060797a138394781a3e1d86339e7b803

**Comment by poko-m2ms** [comment]
Investigation: Both windows (report issue + submit idea) are raised. Visible is the one created later on the page (if buttons 'Report issue' and 'Submit idea' are swapped 'Report issue' dialog window will be always raised)
