### ISSUE TITLE
[CHILD OF #367] When first opening a target, turn on only first ligand and protein of the first site 

### ISSUE THREAD

**Issue by phraenquex** [m2ms/fragalysis-frontend#391]
This is the thing that was requested in #367 but not properly fixed (grrr):

When first going into a protein/target from the main page, turn on _only_ the first ligand and protein of the first site.  (NOT all ligands, which was what I had indeed requested back in April or something.)

**Comment by tibor-postek-m2ms** [comment]
This is done in  #367

**Comment by tibor-postek-m2ms** [comment]
merged in `rhs-filter` branch

**Comment by phraenquex** [comment]
Thanks for finally fixing.

But...  sorry, thought this would be obvious:  it must also centre on that ligand.  (ONLY for this very first ligand.)

**Comment by phraenquex** [comment]
Moving back to "Current milestone" swimlane.
