### ISSUE TITLE
Test of #163

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#393]
- Version: 0.8.7
- Name: Frank von Delft
- Email: frank.vondelft@sgc.ox.ac.uk
- Description: Checking if the feature requests are fixed
- Reducers: https://github.com/m2ms/fragalysis-assets/blob/master/Reducers-1593357984622102008.json?raw=false

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/Screenshot-1593357978319494570.png?raw=true)

**Comment by phraenquex** [comment]
Just a test - close it.
