### ISSUE TITLE
When I select another tab, the RHS filter jumps to the left corner of site

### ISSUE THREAD

**Issue by teriraj** [m2ms/fragalysis-frontend#395]
1. The tab on RHS is opened
2. The RHS filter is opened on the tab
3. When I select another tab, the RHS filter jumps to the left corner of site

Video: https://www.loom.com/share/74bf22697a3d497aba4455e675a8b3f1

![image](https://user-images.githubusercontent.com/65952633/86091198-c1187180-baab-11ea-8ae8-e36db3296f91.png)

**Comment by boriskovar-m2ms** [comment]
The filter will be turned on when switching tabs with custom datasets.
