### ISSUE TITLE
Checkbox "with inspiration" in RHS filter works incorrectly

### ISSUE THREAD

**Issue by teriraj** [m2ms/fragalysis-frontend#397]
1. Open the tab on RHS
2.  Click to the filter button - modal is opened
3. Click to checkbox - checkbox is active - 0 matches found - but there are some computed inspirations in the tab 
Video: https://www.loom.com/share/7297e77d64b645898c4dd93ec9cd17c1

**Comment by boriskovar-m2ms** [comment]
For now the check box will be hidden and actual bug fixed in the future.

**Comment by boriskovar-m2ms** [comment]
As a workaround the checkbox is now hidden
