### ISSUE TITLE
Mouse controls in 3D view

### ISSUE THREAD

**Issue by frantisekrusnak** [m2ms/fragalysis-frontend#4]
As a user I want to be able to view abbreviations and descriptions for mouse controls of 3D view.

**Comment by veronikabelusikova** [comment]
scroll-ctrl --> move near clipping plane
scroll-shift --> move near clipping plane and far fog
when I scroll + ctrl - I don't see any change, when I scroll + shift, only one visible change is far fog, move near clipping plane is not working

drag-ctrl-right --> pan/translate hovered component - whole scene is rotating, not only hovered component
drag-ctrl-left --> rotate hovered component - whole scene is moving, not rotating hovered component
also there is a mistake in **_"hovered"_** word:
![typo](https://user-images.githubusercontent.com/60730965/74632496-c78ef800-515f-11ea-956b-6246b8ca6ffa.PNG)

**Comment by matej-vavrek** [comment]
Mouse controls are same as [defaults in documentation](http://nglviewer.org/ngl/api/manual/interaction-controls.html#controls) and their behaviour is also same as in [their example](http://nglviewer.org/ngl/?script=showcase/ferredoxin).
