### ISSUE TITLE
Fragalysis beta bugs/features - priorities

### ISSUE THREAD

**Issue by tibor-postek-m2ms** [m2ms/fragalysis-frontend#40]
4.
- [x] Remove download YANK button
- [x] Move Download button to Header

5.
- [x] “Clear selection” button: clear the filters
6.
- [x] Viewer controls:
_- [ ] popup behaviour - like Office property editors_
- [x] Dont show vectors in display controls
- [x] all fixed width, and with a border around them to make them more obvious
- [x] get rid of header,
- [x] 3 buttons tight together
- [x] In the settings panel, the hover-ver for “clip near” is covered by the settings title at the top
![image](https://user-images.githubusercontent.com/57392303/74233529-24eff880-4ccb-11ea-87f8-30dbf034b8b2.png)

9. Sort-filter behaviour:
![image](https://user-images.githubusercontent.com/57392303/74155745-61f9b380-4c15-11ea-9af1-d556d8132d59.png)
- [x] slide out modal over 3D pane, without inactivating whole page
- [x] apply changes instantly, not on “apply”
- [x] everything should remain active - just slide in-out.
- [x] third the width (less than half):  squish all icons, labels two rows if necessary, sliders far narrower
- [x] The hit navigator box changes size, when I clear filter

**Comment by reskyner** [comment]
up-to-date version of all notes and mock-ups: https://diamondlightsource.atlassian.net/wiki/spaces/FRAG/pages/11108353/Fragalysis+beta+bugs+features+-+priorities

**Comment by veronikabelusikova** [comment]
“Clear selection” button: when filter is active and I click "clear selection", all sites are cleared, but also "Sort/filter" button is not active - it is not possible to close filter modal window. User have to select another site to make this button active again...
