### ISSUE TITLE
Picking compounds is not working correctly

### ISSUE THREAD

**Issue by veronikabelusikova** [m2ms/fragalysis-frontend#41]
https://fragalysis.apps.xchem.diamond.ac.uk/viewer/react/preview/target/DCLRE1AA

Picking compounds is not working correctly. 
When I pick a molecule, another molecule is selected (molecule on the left side of selected). 
Also when I pick a molecule > shift + click, molecule should be displayed in NGL viewer, but it is not.

**Comment by tibor-postek-m2ms** [comment]
- [ ] update selected compound class in redux

**Comment by veronikabelusikova** [comment]
- [ ]  update selected compound class in redux
- [ ]  uncheck selected compounds in case of selected compounds in selected class
- [ ]  first compound doesnt change opacity by shift + click

**Comment by veronikabelusikova** [comment]
When some compounds are selected (colored) and then I click "Clear selection button", Number picket in Summary info is "0" - correct, but selected compounds are still colored.
