### ISSUE TITLE
zooming in to selected molecule

### ISSUE THREAD

**Issue by fragalysis-reporter** [m2ms/fragalysis-frontend#413]
- Version: 0.8.8
- Name: Anthony Aimon
- Email: anthony.aimon@diamond.ac.uk
- Description: Not an idea but a potential issue
When selecting a fragment hit, the ngl viewer doesn't automatically zoom in to show the bound ligand. 
- Reducers: https://github.com/m2ms/fragalysis-assets/blob/master/Reducers-15946337311356261.json?raw=false

![screenshot](https://github.com/m2ms/fragalysis-assets/blob/master/Screenshot-1594633726840609823.png?raw=true)

**Comment by reskyner** [comment]
That's a feature rather than a bug - if you use the round target icon next to a ligand in the hit navigator, it will centre on that ligand
