### ISSUE TITLE
Sometimes, response to the "Share" button is very slow, and URL takes long to load

### ISSUE THREAD

**Issue by phraenquex** [m2ms/fragalysis-frontend#440]
(Already mentioned in #418, but opening new ticket.)  
(Maybe covered by #426 already, in which case close this one please.)

When I hit the Share button, it takes many many seconds to bring up the share modal - especially first time I'm on the page (I think).

Expected behaviour:

- quicker response 
- if not possible, make the progress bar run
- render URL more quickly.

**Comment by ag-m2ms** [comment]
I managed to reproduce the issue in the dev environment while having some of the compounds from the AllesandroContini in Mpro target selected.
It looks like the response from the endpoint /snapshots/ takes long time to download. The response is around 1.2 MB large and may take couple of seconds or even more to load depending on the internet connection speed or server traffic.
Other than that, I haven't noticed any potential bottlenecks in the FE (no number crunching or any CPU heavy operations).
![image](https://user-images.githubusercontent.com/68894622/96424614-39da3f80-11fb-11eb-8146-479a3b8e0283.png)
