### ISSUE TITLE
Model display issues: waters displayed, hydrogens not hidden

### ISSUE THREAD

**Issue by phraenquex** [m2ms/fragalysis-frontend#443]
For some time now, waters are no longer being displayed - I only just noticed, but it must have been since July or earlier.

Also, hydrogen atoms are being displayed - but they should be turned off.  E.g. in this snapshot, one protein is correct (x0598) and one wrong (mac-c137).  
https://fragalysis.diamond.ac.uk/viewer/react/projects/279/229

**Comment by ak-m2ms** [comment]
Problem with not displayed water was found in #241. 
Previously, the C - "showComplex" was divided into the P - "showHitProtein" and C - "showComplex" function. It could have caused a problem (#228).

**Comment by phraenquex** [comment]
@boriskovar-m2ms asks for more detail, screenshots etc.  @reskyner will provide some.
