### ISSUE TITLE
After saving & reloading - the tab is not selected on RHS

### ISSUE THREAD

**Issue by teriraj** [m2ms/fragalysis-frontend#477]
RHS before saving
![image](https://user-images.githubusercontent.com/65952633/101739202-81789b80-3ac7-11eb-901c-139558031fba.png)

RHS after saving and reloading
![image](https://user-images.githubusercontent.com/65952633/101739333-a5d47800-3ac7-11eb-93d4-b7ea1a9456a5.png)

The views before saving and after saving should look the same

**Comment by boriskovar-m2ms** [comment]
Saving now doesn't reload page so this ticket is now invalid.
