### ISSUE TITLE
Hit navigator - layout

### ISSUE THREAD

**Issue by tibor-postek-m2ms** [m2ms/fragalysis-frontend#48]
- [x] (another mock-up)
![image](https://user-images.githubusercontent.com/57392303/74306988-7ac4af00-4d64-11ea-89ae-973ba9f3bc52.png)
- [x] quality metrics - MUCH narrower, squish into single icon-let
- [x] Compound much bigger, at least 2x wider
- [x] Change properties into table:  only one header at top, single row
- [x] Remove target name from label
- [x] Numbers - decimal points.  none: MW, TPSA.  one: logP
- [x] #cpd - make it work - move to backend
- [x] #vectors - total (pickable)
- [x] display toggles:  better contrast (check ICM, suggest you copy)
- [x] move quality labels and title label next to ALCV buttons

- [x] Fix open sort dialog

**Comment by tibor-postek-m2ms** [comment]
![image](https://user-images.githubusercontent.com/57392303/74413493-cd26ce00-4e3f-11ea-9bfa-4c575e23264d.png)
I suggest to make fixed width of values (numbers.) Truncate of values by suitable count of characters should solve the problem. But question is
1. Count of characters?
2. Rounding of numbers?

**Comment by reskyner** [comment]
Numbers - decimal points. none: MW, TPSA. one: logP

**Comment by tibor-postek-m2ms** [comment]
> Numbers - decimal points. none: MW, TPSA. one: logP

yes, thanks and next which number of characters for every value (number si character too)
for example **MW [3characters]**, **logP [3characters - number + point + number]**

**Comment by reskyner** [comment]
max: MW [3 - rounded to whole number] logP [2 - rounded to 1 dp] TPSA [3 - rounded to whole number]  everything else 3 characters

**Comment by tibor-postek-m2ms** [comment]
#vectors from followed curl you can make sum of vectors
`curl 'http://localhost:8080/api/vector/1527/' -H 'Connection: keep-alive' -H 'Accept: application/json, text/plain, */*' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36' -H 'Sec-Fetch-Site: same-origin' -H 'Sec-Fetch-Mode: cors' -H 'Referer: http://localhost:8080/viewer/react/preview/target/NUDT5A' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: sk-SK,sk;q=0.9,cs;q=0.8,en-US;q=0.7,en;q=0.6' -H 'Cookie: _lr_uf_-eoalzb%2Ffragalysis=1c2ce53e-ef2c-4608-8a3b-a2bbef5a3df0; csrftoken=XSCkaYWSFnYA8mDWuH8W8WJ975aK751edgypNtsmKv3j5fQafYfQBxAH3Vnx0RtZ; messages="32c6efc016797d1a244112aa7f3a20d7acf22aae$[[\"__json_message\"\0540\05425\054\"Login succeeded. Welcome\054 pavol.brunclik@m2ms.sk.\"]\054[\"__json_message\"\0540\05425\054\"Login succeeded. Welcome\054 pavol.brunclik@m2ms.sk.\"]\054[\"__json_message\"\0540\05425\054\"Login succeeded. Welcome\054 pavol.brunclik@m2ms.sk.\"]\054[\"__json_message\"\0540\05425\054\"Login succeeded. Welcome\054 pavol.brunclik@m2ms.sk.\"]\054[\"__json_message\"\0540\05425\054\"Login succeeded. Welcome\054 pavol.brunclik@m2ms.sk.\"]]"' --compressed`

**Comment by tibor-postek-m2ms** [comment]
We need detail specification of following properties:
- Velec - wrong number?
- add electron density selector

**Comment by tibor-postek-m2ms** [comment]
Hi Tibor, Frank and I had another go. Can we force this element to be fixed width (the whole left hand column) and:
- [ ] move the molecule image to the right hand side
- [ ] move the id, quality labels and viewer controls to one row (top left)
- [ ] move properties table to one row (bottom left)
- [ ] You can make font sizes smaller if you need to. We need to try to make it as compact as possible
- [ ] always center the numbers and headings in the properties table

**Comment by tibor-postek-m2ms** [comment]
- [ ] Smaller font size of Site

- [ ] borders of properties have gray color

- [ ] tooltip on property

- [ ] smaller height of container (image will be smaller too)

- [ ] eliminate white spaces between quality labels

- [ ] smaller padding of buttons 

- [ ] smaller font size of title label

**Comment by veronikabelusikova** [comment]
- [ ]  quality metrics - MUCH narrower, squish into single icon-let
- [ ]  Compound much bigger, at least 2x wider
- [ ]  Change properties into table: only one header at top, single row
- [ ]  Remove target name from label
- [ ]  Numbers - decimal points. none: MW, TPSA. one: logP
- [ ]  #vectors - total (pickable)
- [ ]  display toggles: better contrast (check ICM, suggest you copy)
- [ ]  move quality labels and title label next to ALCV buttons
- [ ]  Fix open sort dialog
- [ ] move the molecule image to the right hand side
- [ ]  move the id, quality labels and viewer controls to one row (top left)
- [ ]  move properties table to one row (bottom left)
- [ ]  You can make font sizes smaller if you need to. We need to try to make it as compact as possible
- [ ]  always center the numbers and headings in the properties table
- [ ] Smaller font size of Site, fixed width for 2 characters with minimalistic padding
- [ ]  borders of properties have gray color
- [ ]  tooltip on property
- [ ]  smaller height of container (image will be smaller too)
- [ ]  eliminate white spaces between quality labels
- [ ]  smaller padding of ALCV buttons
- [ ]  smaller font size of title label

**Comment by veronikabelusikova** [comment]
Amount of compounds in hit navigator and in right part (compounds on vector to pick) is not always the same number. 
![number of vectors](https://user-images.githubusercontent.com/60730965/74827411-b08e0880-530d-11ea-9229-86468e06f780.PNG)
![number of vectors2](https://user-images.githubusercontent.com/60730965/74827413-b1269f00-530d-11ea-87ec-3277b18ed572.PNG)
Test in Google Chrome - OK, but in Mozzila Firefox  - site properties are incorrectly displayed when there is bugger amount of compounds (more than 2 characters). 
![hit navigator mozzila](https://user-images.githubusercontent.com/60730965/74827247-5e4ce780-530d-11ea-92e2-ce186f615a72.PNG)
Also bigger amount of compounds (5 characters) is not displayed correctly. 
![Capture](https://user-images.githubusercontent.com/60730965/74827262-660c8c00-530d-11ea-842c-532345fb98ad.PNG)
