### ISSUE TITLE
Bugs found during regression testing

### ISSUE THREAD

**Issue by teriraj** [m2ms/fragalysis-frontend#496]
1. Home page - **Create new project** (new project, from snapshot) - after saving the page is not responding, but the new project is created. 
2. **Report issue**
 a) after clicking on the Report issue button, a window for entering an idea is opened. After filling in the form, the issue will be displayed in the github with the label idea.
 b) when I try to report issue without screenshot, after clicking to Submit button it will stuck in loading process - never ending loading
![image](https://user-images.githubusercontent.com/65952633/105142384-d4983200-5afa-11eb-9289-c9843baf68f4.png)

Button **submit idea**
a) with screenshot - OK
b) without screenshot - the same problem as _report issue_ - never ending loading

3. **Download structures** - after clicking the button nothing is downloaded
4. **Mouse controls** - some shortcuts do not work
![image](https://user-images.githubusercontent.com/65952633/105148516-c221f680-5b02-11eb-9978-04d521b265fa.png)

5. **RHS**
Should be: A selected = LPC selected = dark blue
The A button is now colored medium blue
![image](https://user-images.githubusercontent.com/65952633/105174413-d118a100-5b22-11eb-9e81-28b55d8daa4a.png)

6. **RHS** - selected tab
Select some molecules and turn on some toggles
![image](https://user-images.githubusercontent.com/65952633/105175048-b98de800-5b23-11eb-8737-aeca45eaa164.png)
Open selected tab and turn off selected toggles
![image](https://user-images.githubusercontent.com/65952633/105175155-d4f8f300-5b23-11eb-9cc2-b8c84384fc2f.png)
nothing is displayed in the NGL view, but the buttons remain dark blue
when I open another tab and return to the selected tab, the buttons are already deselected

7. **RHS**
Cross reference 
if a compound is selected in the cross reference and then I open the selected tab, the cross reference window jumps to the upper left corner
![image](https://user-images.githubusercontent.com/65952633/105176896-2d30f480-5b26-11eb-9515-824a70ec4e79.png)

8.  Cross reference&inspiration window: https://github.com/m2ms/fragalysis-frontend/issues/490
9. **RHS** - the toggles on the top should be medium blue in this case
![image](https://user-images.githubusercontent.com/65952633/105322925-cb29cb00-5bc9-11eb-8e5b-bfaa4d0fa7ff.png)

10. **Undo** when switching on L and V
If I turn on the buttons in sequence:
L, V ---> then in the Undo action first turns off V and then L.
If I turn on the buttons in sequence:
V, L ---> then turns off both buttons at the same time during the Undo action.

11. Saving snapshot 
Current snapshot ---> do some changes -----> save as new snapshot
![image](https://user-images.githubusercontent.com/65952633/105463710-c11ecf80-5c90-11eb-8b09-7573043e988c.png)
The newest snapshot is no. 625
![image](https://user-images.githubusercontent.com/65952633/105463995-25da2a00-5c91-11eb-8526-4c9e72e557f8.png)
however as current snapshot is marked snapshot no. 622
![image](https://user-images.githubusercontent.com/65952633/105464065-41ddcb80-5c91-11eb-9f56-15984ceba78d.png)

**Comment by boriskovar-m2ms** [comment]
For each bug a separate ticket was created.
