### ISSUE TITLE
Unify the behavior of sites and balls

### ISSUE THREAD

**Issue by teriraj** [m2ms/fragalysis-frontend#498]
You can mark sites by clicking in the checkbox or by clicking on the balls. 

![image](https://user-images.githubusercontent.com/65952633/105017281-e2d74700-5a43-11eb-828b-54e1423a4f9e.png)

If any compound is selected in the hit navigator
![image](https://user-images.githubusercontent.com/65952633/105017837-8de80080-5a44-11eb-8305-59f0387322f9.png)

and I deselect sites:
1. by clicking on the checkbox 

![image](https://user-images.githubusercontent.com/65952633/105018073-d3a4c900-5a44-11eb-950c-5140cf52251c.png)

2. by clicking on the  balls

![image](https://user-images.githubusercontent.com/65952633/105018178-f46d1e80-5a44-11eb-850b-5049e4ecf108.png)

----> Selected compounds should remain displayed in both cases

**Comment by phraenquex** [comment]
To confirm:  this bug probably does _not_ need to be fixed, it will almost certainly be superceded by #493
