### ISSUE TITLE
Track reported issue

### ISSUE THREAD

**Issue by frantisekrusnak** [m2ms/fragalysis-frontend#5]
As a user I want to know status   of reported issues.

**Comment by matej-vavrek** [comment]
After an issue is submitted, it is available in GitHub issues.

**Comment by veronikabelusikova** [comment]
Option “Reported issues” in menu - in menu there is not this option
Also there is no overview of reported issues in the application.

**Comment by veronikabelusikova** [comment]
Option "reported issues" is not in Fragalysis application menu. 
It is possible to see reported issues in GitHub.

**Comment by phraenquex** [comment]
Already released, and remaining comments now in ticket #163 - closing this ticket.
