### ISSUE TITLE
Surface is not retained with RHS down button

### ISSUE THREAD

**Issue by phraenquex** [m2ms/fragalysis-frontend#554]
As in title. 
![image](https://user-images.githubusercontent.com/33267937/107346353-830d1280-6abc-11eb-9b4d-6778e91761f1.png)

**Comment by teriraj** [comment]
Cannot be tested because the S button on the RHS cannot be selected
Also toggles PC are broken, also mass PC.
(also Cross reference window)

**Comment by boriskovar-m2ms** [comment]
@reskyner it seems that this problem is related to the missing cartoon. The pdb_info are missing.

**Comment by phraenquex** [comment]
Sounds like we should close this - thanks for diagnosing!

@reskyner , I think we need a different ticket, one for the backend upload, that gives uploaders more detailed feedback on things they haven't entered.  This may not be simple...
