### ISSUE TITLE
Some ligand qualities not working (e.g. PHIPA-x11310)

### ISSUE THREAD

**Issue by reskyner** [m2ms/fragalysis-frontend#639]
Tyler says something to do with missing atom definitions or colours

**Comment by TJGorrie** [comment]
One issue may be that the good atoms are not being obtain sufficiently:

https://github.com/m2ms/fragalysis-frontend/blob/allfunctionality/js/components/nglView/renderingHelpers.js#L169

This line should be:
`var regexp = /[(H|He|Li|Be|B|C|N|O|F|Ne|Na|Mg|Al|Si|P|S|Cl|Ar|K|Ca|Sc|Ti|V|Cr|Mn|Fe|Co|Ni|Cu|Zn|Ga|Ge|As|Se|Br|Kr|Rb|Sr|Y|Zr|Nb|Mo|Tc|Ru|Rh|Pd|Ag|Cd|In|Sn|Sb|Te|I|Xe|Cs|Ba|La|Ce|Pr|Nd|Pm|Sm|Eu|Gd|Tb|Dy|Ho|Er|Tm|Yb|Lu|Hf|Ta|W|Re|Os|Ir|Pt|Au|Hg|Tl|Pb|Bi|Po|At|Rn|Fr|Ra|Ac|Th|Pa|U|Np|Pu|Am|Cm|Bk|Cf|Es|Fm|Md|No|Lr|Rf|Db|Sg|Bh|Hs|Mt)]/g;`

Likewise there also need to be colour definitions for all Atoms here:
https://github.com/m2ms/fragalysis-frontend/blob/allfunctionality/js/components/nglView/constants/index.js#L132-L151

The atom colour definitions can be found here: (I think the Atoms have to be capitalised)
http://jmol.sourceforge.net/jscolors/
