### ISSUE TITLE
GUI layout (epic 1)

### ISSUE THREAD

**Issue by phraenquex** [m2ms/fragalysis-frontend#650]
Front-end is ugly for many many people.

Problems include:
* barely any NGL visible
* large amounts of whitespace
* irrelevant stuff blocking out screen

Likely fixes:
* hide RHS by default
* obvious widgets to hide strips of LHS 
* place project trajectory under NGL (?)
* review LHS things
* rationalise buttons (e.g. show V for RHS; merge Q/D)
* perspectives
* ability to drag compounds up/down
* better 2D rendering of molecules (Tim says RDKit has improved)

**Comment by boriskovar-m2ms** [comment]
agreed tasks:
<html><body>
<google-sheets-html-origin><style type="text/css"></style>

Hideable LHS, RHS, RHS hidden by default
--
place project trajectory under NGL
rationalise buttons (e.g. show V for RHS; merge Q/D)
ability to drag compounds up/down
better 2D rendering of molecules (Tim says RDKit has improved)


</body>
</html>

**Comment by phraenquex** [comment]
Only remaining feature: is better rendering of molecules - that will happen under ALC - new ticket #762 

Go forwards to staging.
