### ISSUE TITLE
Site info in cluster navigator

### ISSUE THREAD

**Issue by frantisekrusnak** [m2ms/fragalysis-frontend#66]
1.	Defaults on entry:

- [x] 1.	White background 

- [x] 2.	Activate some cluster by default (**first site**)

- [ ] 3.	Activate first hit of first cluster, display all

**Comment by boriskovar-m2ms** [comment]
First site will be activated as a temporary solution until we found a way how to get site size (number of fragments) from the backend

**Comment by tibor-postek-m2ms** [comment]
- [ ] Add version of app to menu

**Comment by veronikabelusikova** [comment]
Defaults on entry:
- [ ]  1. White background
- [ ]  2. Activate some cluster by default (first site)
- [ ]  3. Activate first hit of first cluster, display all

- [ ]  Add version of app to menu
- [ ]  Align quality labels to left
