### ISSUE TITLE
Hit navigator: drop-down to colour red the value outside rule of 3 or 5 or none - left of sort/filter button. Default: rule-of-3.  CURRENTLY BREAKS PAGE

### ISSUE THREAD

**Issue by frantisekrusnak** [m2ms/fragalysis-frontend#67]

**Comment by matej-vavrek** [comment]
8. Hit navigator: drop-down to colour red the value outside rule of 3 or 5 or none - left of sort/filter button. Default: rule-of-3.
- [ ] move dropdown
- [ ] colour unmatched items to red

**Comment by phraenquex** [comment]
Can we try colouring just inside the boxes.  And in fact, let's turn it round:  colour the boxes green when the value is correct (rather than red when it's wrong).

Also use pale colours:  pale green is better.

When you're done, remember to post the link to the snapshot on the git ticket.

**Comment by matej-vavrek** [comment]
Colour matched values with predefined filter now.

Snapshot:
https://fragalysis-boris.apps.xchem.diamond.ac.uk/viewer/react/snapshot/2503cfe6-dec9-4643-8a6b-103f577a8850

An bug with wrong save/load of filter in session occured #187

**Comment by phraenquex** [comment]
Latest status:  this completely breaks the page, throws a massive error and forces you to reload everything.
But moving into backlog for now, because we're running out of money.
