### ISSUE TITLE
Release of Tag feature broke several targets

### ISSUE THREAD

**Issue by phraenquex** [m2ms/fragalysis-frontend#681]
The new Tags transition breaks at least several targets, including:
* https://fragalysis.diamond.ac.uk/viewer/react/preview/target/PGN_RS02895PGA
* https://fragalysis.diamond.ac.uk/viewer/react/preview/target/HAO1A

Sounds like a back-end problem - maybe just a (fairly simple) database curation problem?

Very high priority;  and if not quickly fixable, we need to roll back the Tag release.

**Comment by duncanpeacock** [comment]
@boriskovar-m2ms 

There seems to be a common thread with these targets - they have no tags set up (i.e. they haven't been reloaded so the new tags have not been created). 

Boris, Can you check what happens on the front end when this happens?  i.e the tags_sets, tags_Info and tags_categories in the target_molecules api reply are empty?

Thanks.
Then we can work out what to do..

**Comment by phraenquex** [comment]
@boriskovar-m2ms :  Frontend needs to handle empty groups gracefully

**Comment by phraenquex** [comment]
Duplicate of #688 , so closing this one.
