### ISSUE TITLE
Inclusive/exclusive tag selector slider is not clear enough 

### ISSUE THREAD

**Issue by rsanchezgarc** [m2ms/fragalysis-frontend#689]
The terms Inclusive/exclusive are not clear enough. We need to rename them and explain the behaviour using a tooltip.

Inclusive  -> combine Union "Only the compounds labelled with all the active tags will be selected"
Exclusive -> combine Intersection: "Any compound labelled with any of the active tags will be selected"

**Comment by rsanchezgarc** [comment]
I realised that it is better to add the name of the selection type to the description

Inclusive -> combine Union "Union: Only the compounds labelled with all the active tags will be selected"
Exclusive -> combine Intersection: "Intersection: Any compound labelled with any of the active tags will be selected"

**Comment by boriskovar-m2ms** [comment]
I think the description for the Union and Intersection should be switched:
Union: "Union: Any compound labelled with any of the active tags will be selected"
Intersection: "Intersection: Only the compounds labelled with all the active tags will be selected"

Or description should describe what will happen when user clicks the button?

**Comment by rsanchezgarc** [comment]
It is ok now.
