### ISSUE TITLE
Add copy SMILES button in the 2D image of the molecule.

### ISSUE THREAD

**Issue by rsanchezgarc** [m2ms/fragalysis-frontend#692]
There is no easy way of retrieving the smiles of the compounds in the left-hand side pane. We need a way to retrieve the SMILES of a given molecule easily.
A button for each compound, similar to the tag button, could be added to copy the SMILES

**Comment by tdudgeon** [comment]
Agreed. This would be very useful. It took me 15 mins to track down the SMILES of a molecule I wanted yesterday!
Also, would be useful to copy the molfile in case you want the 3D coordinates.

**Comment by phraenquex** [comment]
@boriskovar-m2ms how much work would it be to put [copy smiles] directly under the ALPC... buttons?

**Comment by tdudgeon** [comment]
@phraenquex Sorry to speak for Borris, but I don't think he has the SMILES. It needs to be added to what the back end provides. Not too difficult, but just needs to be done and then added to front end.

**Comment by tdudgeon** [comment]
Actually, maybe he does already have the SMILES as he presumably sends it for rendering.

**Comment by phraenquex** [comment]
@boriskovar-m2ms can you clarify?

**Comment by boriskovar-m2ms** [comment]
It seems I got SMILES for each molecule
![image](https://user-images.githubusercontent.com/16878338/153338346-6c21f1c2-94c3-4a1d-acfd-d2fc7fc1ea44.png)

And it should take a few hours

**Comment by phraenquex** [comment]
Been there for a long time now - zombie ticket.
