### ISSUE TITLE
New idea submission

### ISSUE THREAD

**Issue by frantisekrusnak** [m2ms/fragalysis-frontend#7]
As a user I want to submit new ideas and improvements.

**Comment by veronikabelusikova** [comment]
There are some parameters missing in dialog: _**version, attachment**_ (only screenshot is attached, but other attachment it is not possible to add), **_Date and time_** > this information is in github only as "time in hours, days, minutes" AGO

- Name and Email are not automatically filled, I have to enter them manually

- New idea is submitted via a form located in the menu > **"submit idea"** item is missing in menu

- A link to the submitted idea is returned to the user after successful report submission > _where I can find this link?_

**Comment by veronikabelusikova** [comment]
**Actually done:** 
- Submission (dialog) contains:
o	Version
o	Name
o	Email
o	Short description of the idea (title)
o	Description of the idea
o	Screenshot of current page
o	Date and time
-	After an idea submission is automatically created an issue in GitHub with its name, description and an “enhancement” label --> issue has "idea" label, not "enhancement". 
-	Submission is stored in GitHub.
-	A link to the submitted idea is returned to the user after successful report submission and the issue creation in GitHub.
-	Submit idea button (icon) should be placed at top bar.

**To do or to be discussed if it is required:** 
-	New menu option: “Submit new idea”
-	Submission (dialog) contains:
o	Email --> dialog contains email, but it is not displayed in github
o	Attachments --> only screenshot is attached, there is not possibility to add more attachements
o	Screenshot of current page
o	Session (created in the moment of idea submission)

-	The Application shall fill Name and Email parameters for registered user --> I have to enter them manually
-	New idea is submitted via a form located in the menu --> in application menu there is not item "submit idea"

**Comment by phraenquex** [comment]
Veronika's ideas are good, but not needed for this ticket; closing this ticket, and transferring those points to a new ticket.
