### ISSUE TITLE
Track submitted ideas

### ISSUE THREAD

**Issue by frantisekrusnak** [m2ms/fragalysis-frontend#8]
As a user I want to know status of submitted ideas.

**Comment by matej-vavrek** [comment]
After a new idea is submitted, it is available in GitHub issues.

**Comment by veronikabelusikova** [comment]
It is not clear, if overview of submitted ideas should be at github or as an item of Fragalysis application menu.

**Comment by veronikabelusikova** [comment]
At the moment in Fragalysis application there is not possible to display overview of submitted ideas. Ideas are stored only in GitHub with "idea" label. It is possible to filter issues by label and select only issues with "idea".

**Comment by phraenquex** [comment]
I agree, this should stay in github;  and we will transfer them to the Fragalysis wiki too.
Veronika, the link to that is here, if you don't have it yet:
https://diamondlightsource.atlassian.net/wiki/spaces/FRAG/overview
Closing this ticket.
