### ISSUE TITLE
Error 500 for Discourse new-project call - api fix

### ISSUE THREAD

**Issue by NikolaStryckova** [m2ms/fragalysis-frontend#886]
**Descriptions:** After creating the project there is an error in the console about api/discourse_post /

**Steps:**
- click the plus button on the home page to create a new project,
- fill in the required data for creating the project, check to create the topic of the discourse,
- confirm the creation of the project,
- we see console error

**Version:** 0.10.93
![2022-06-06_09h38_23](https://user-images.githubusercontent.com/92084528/172157104-5b5c4397-0b7a-433a-a090-3934f140ed74.png)

**Comment by phraenquex** [comment]
@boriskovar-m2ms to give @alanbchristie precise bug details.
