### ISSUE TITLE
[Application] Wrong displaying when resizing page

### ISSUE THREAD

**Issue by veronikabelusikova** [m2ms/fragalysis-frontend#92]
- [x] Wrong displaying when resizing page:

Google Chrome: 
![resize](https://user-images.githubusercontent.com/60730965/74945264-bc55f980-53f7-11ea-8339-ea663f091ccf.PNG)

 Mozilla Firefox
![resize mozzila](https://user-images.githubusercontent.com/60730965/74945297-c841bb80-53f7-11ea-8fbe-2d224556618c.PNG)

Also when I zoom page, application is displayed wrong in 100%
![resizing3](https://user-images.githubusercontent.com/60730965/74935517-a8ef6200-53e8-11ea-8de5-7dc4c7398d71.PNG)

less than 100% is OK, but 150% and more is again wrong displayed: 
![resizing1](https://user-images.githubusercontent.com/60730965/74935585-c91f2100-53e8-11ea-8939-369422f4f38b.PNG)
![resizing2](https://user-images.githubusercontent.com/60730965/74935586-c9b7b780-53e8-11ea-9544-d497de792687.PNG)

**Comment by boriskovar-m2ms** [comment]
![image](https://user-images.githubusercontent.com/16878338/75010269-07662000-547d-11ea-8f9c-29f469092505.png)
Because of the two lines spanning of the header bar please remove the target name from the Download xxx structures
