### ISSUE TITLE
[LHS] Filter doesn't work  

### ISSUE THREAD

**Issue by NikolaStryckova** [m2ms/fragalysis-frontend#928]
**Description:** It is not possible to filter compounds. After selecting the required parameters, no compounds will be displayed. The buttons for Filter/Sort and Edit tags will become inactive.

**Version:** 0.10.121

https://user-images.githubusercontent.com/92084528/179964584-c8c76a7f-ea00-4dc2-b490-0ef95227aac0.mp4

**Comment by rsanchezgarc** [comment]
@boriskovar-m2ms 

If you accidentally filter out all the compounds by setting a too large threshold(s), then there is no way to get the filter button back and, as a consequence, visualise any compound

**Comment by rsanchezgarc** [comment]
@boriskovar-m2ms 

Filters work ok.
The "is shown" checkbox does not work.
