### ISSUE TITLE
Sometimes the snapshot is not restored

### ISSUE THREAD

**Issue by boriskovar-m2ms** [m2ms/fragalysis-frontend#935]
Sometimes the snapshot is not restored and no fragments are displayed in Hit Navigator. There is no backend related error in the console.

Might be related to #796

**Comment by rsanchezgarc** [comment]
There are several related problems.
@boriskovar-m2ms @alanbchristie 

1) In many cases I have to reload the page to get something loaded. It also happens on the landing page.
2) Sometimes the content does not load for a long time or until I actively click on some of the RHS sets.
