### ISSUE TITLE
[Filter] Filter property # available follow-up cmpds. wrong value

### ISSUE THREAD

**Issue by NikolaStryckova** [m2ms/fragalysis-frontend#949]
**Description**: Filter property _# available follow-up cmpds. (#cpd)_ has wrong value. When I click on this value, two sliders appear in the hit navigator window. I don't see the filtered value in the compound overview.

**Version**: 0.10.124

![2022-08-03_13h17_42](https://user-images.githubusercontent.com/92084528/182595806-4a93baa4-4e3d-43c6-9974-66608a7c146b.png)

**Comment by rsanchezgarc** [comment]
@NikolaStryckova. In which example did you try it?
