### ISSUE TITLE
[Filter] Filter property valec electrons has different design of scale

### ISSUE THREAD

**Issue by NikolaStryckova** [m2ms/fragalysis-frontend#950]
**Description:** Filter property valec electrons -> filtering range has different design of scale
**Version:** 0.10.12
![2022-08-03_13h33_36](https://user-images.githubusercontent.com/92084528/182598577-cc7ce06a-f09b-4180-bd1f-9492687e0458.png)
4

**Comment by boriskovar-m2ms** [comment]
It's because logP is real number # valence electrons is real value
