### ISSUE TITLE
[RHS] Transferring surface from compound above to the one below causes error

### ISSUE THREAD

**Issue by NikolaStryckova** [m2ms/fragalysis-frontend#951]
**Description:** We can use arrows buttons to transfer everything from the compound above to the one below. Transferring surface causes console error.
**Version:** 0.10.124
![2022-08-03_14h20_56](https://user-images.githubusercontent.com/92084528/182606255-e3249b6a-29f5-4b0b-a5ca-1075c840f594.png)

**Comment by boriskovar-m2ms** [comment]
Works for me locally and also on boris stack. Tried exactly same compounds in the picture and many more.
