### ISSUE TITLE
[RHS] Filter causes wrong compound list displaying

### ISSUE THREAD

**Issue by NikolaStryckova** [m2ms/fragalysis-frontend#953]
**Description:** Filter causes wrong compound list displaying. (In the video you can see a functional filter on the LHS).
It is also not possible to cancel the display of the filter using the trash icon (as it works on the LHS).
**Version:** 0.10.124

https://user-images.githubusercontent.com/92084528/182614395-4bb8c15e-0842-4d21-8d23-093872cf9f0f.mp4

**Comment by boriskovar-m2ms** [comment]
Could not replicate. Tried the steps in 1080p and also 1440p resolutions.
