### ISSUE TITLE
Automatic depth queuing

### ISSUE THREAD

**Issue by boriskovar-m2ms** [m2ms/fragalysis-frontend#97]
Currently NGL view is very inconsistent when it comes to centering fragment hit based on the selection (ligand, complex or vector). 

There is a need to investigate what are possibilities when it comes down to controlling this behavior. 
Extensive documentation can be found here: http://nglviewer.org/ngl/api/

**Comment by tibor-postek-m2ms** [comment]
Initial scenario:

1. Select ligand and its position save to current state
2. Select vector of previous molecule and use previous data to zoom
3. Otherwise we can use auto zoom

**Comment by phraenquex** [comment]
I don't understand the rules you implemented;  and they seem wrong.  Please explain again.

Meanwhile

- The fog and clip values should be: 
 clip near:  45
 clip far:  100
 fog near:  51
 fog far:  58

The auto zoom should be where the molecule, if strecthed out long, takes up 1/3rd of the left-to-right distance of the NGL window.

When we turn on hits that lie in the site that already is in the centre of our view, then do NOT reset the view;  simply load the ligand.
-

**Comment by tibor-postek-m2ms** [comment]
Ok, but we need to have detailed specification of this feature. We can do it next week
@boriskovar-m2ms
